pul_nomad_role: "client"
nomad_client_host_volumes:
  - name: podman-socket
    path: /var/run/podman/podman.sock
    read_only: true
    state: file
nomad_host_volumes: "{{ nomad_client_specific_host_volumes|default([]) + nomad_client_host_volumes|default([]) }}"
