---
nginx_version: "1.18.0-6ubuntu14.18"
passenger_target_version: "1:6.1.6-1~jammy1"

nginx_passenger_packages:
  - "nginx-core=1.18.0-6ubuntu14.18"
  - "nginx-common=1.18.0-6ubuntu14.18"
  - "passenger=1:6.1.6-1~jammy1"
  - "libnginx-mod-http-passenger=1:6.1.6-1~jammy1"
