---
nginx_version: "1.24.0-2ubuntu7.15"
passenger_version: "1:6.1.6-1~noble1"

nginx_package_names:
  - nginx-core
  - nginx-common

passenger_package_specs:
  - "passenger={{ passenger_version }}"
  - "libnginx-mod-http-passenger={{ passenger_version }}"
