---
passenger_target_version: "1:6.1.6-1~noble1"

nginx_passenger_packages:
  - "nginx-core=1.24.0-2ubuntu7.15"
  - "nginx-common=1.24.0-2ubuntu7.15"
  - "passenger=1:6.1.6-1~noble1"
  - "libnginx-mod-http-passenger=1:6.1.6-1~noble1"
