---
- name: PostgreSQL | create local postgresql database
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: 'UTF-8'
    state: "present"
    login_user: "{{ postgres_admin_user }}"
    owner: "{{ item.owner | default(postgres_admin_user) }}"
  #  delegate_to: '{{ postgres_host }}'
  when:
    - running_on_server
    - postgresql_is_local | bool
    - postgresql_databases|length > 0
  changed_when: false
  become: true
  become_user: "{{ postgres_admin_user }}"
  loop: "{{ postgresql_databases }}"
