---
# the postgresql role covers server builds and client installs
# projects with a postgres database on a shared server should run client.yml
# when building a new or updated postgres server, run server.yml
- name: Include client tasks
  ansible.builtin.include_tasks: client.yml
  when: postgres_db_type==client

- name: Include server tasks
  ansible.builtin.include_tasks: server.yml
  when: postgres_db_type==server
