---
# we have two types of postgres servers: standalone and clustered
# we have a shared cluster and a dedicated cluster for figgy
# clusters run on Ubuntu; the standalone server for Tower runs on RHEL
- name: Include OS-specific vars
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific install tasks
  ansible.builtin.include_tasks: install_{{ ansible_os_family | lower }}.yml

- name: Ensure PostgreSQL is enabled and started
  ansible.builtin.service:
   name: "{{ postgres_service_name }}"
   state: started
   enabled: true

- name: Add logrotate rules
  ansible.builtin.template:
    src: "../../common/templates/logrotate_rules.j2"
    dest: "/etc/logrotate.d/{{ item.name }}"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ postgresql_logrotate_rules }}"
  when:
    - postgresql_logrotate_rules is defined
    - postgresql_logrotate_rules | length > 0

- name: Add replication postgresql configuration
  ansible.builtin.template:
    src: replication.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/conf.d/replication.conf"
    mode: "0644"
  when:
    - running_on_server
    - postgresql_cluster_member == true
  notify: restart postgresql

- name: Restart leader postgres server
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: started
  when:
    - postgresql_is_local | bool
    - postgresql_leader == true

- name: Ensure pgpass
  ansible.builtin.template:
    src: pg_pass.j2
    dest: "~/.pgpass"
    mode: "0600"
    owner: postgres
  changed_when: false
  when: postgresql_is_local | bool
  become: true

- name: Configure warm standby leader
  ansible.builtin.include_tasks: warm_standby_leader.yml
  when:
    - postgresql_cluster != false
    - inventory_hostname == postgresql_cluster.leader

- name: Configure warm standby follower
  ansible.builtin.include_tasks: warm_standby_follower.yml
  when:
    - postgresql_cluster != false
    - inventory_hostname in postgresql_cluster.followers

- name: Configure logical replication on cluster leader
  ansible.builtin.include_tasks: logical_replication.yml
  when:
    - postgresql_cluster != false
    - inventory_hostname == postgresql_cluster.leader
    - postgresql_logical_replication != false

# - name: Create databases
#   ansible.builtin.include_tasks: create_db.yml

- name: PostgreSQL | create local postgresql database
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: 'UTF-8'
    state: "present"
    login_user: "{{ postgres_admin_user }}"
    owner: "{{ item.owner | default(postgres_admin_user) }}"
  when:
    - running_on_server
    - postgresql_is_local | bool
    - postgresql_databases|length > 0
  changed_when: false
  become: true
  become_user: "{{ postgres_admin_user }}"
  loop: "{{ postgresql_databases }}"

- name: Create users
  ansible.builtin.include_tasks: create_users.yml

- name: Create read-only user
  ansible.builtin.include_tasks: create_read_only_user.yml
  when: application_dbuser_ro_name is defined
  tags: grant_ro_privs
