---
- name: Redis | Download Redis GPG key (ASCII)
  ansible.builtin.get_url:
    url: "{{ redis_apt_key_url }}"
    dest: /tmp/redis.gpg.key
    mode: '0644'

- name: Redis | De-armor Redis GPG key to binary keyring
  ansible.builtin.shell: "gpg --dearmor < /tmp/redis.gpg.key > {{ redis_keyring_path }}"
  args:
    creates: "{{ redis_keyring_path }}"
  become: true

- name: Redis | Ensure keyring permissions
  ansible.builtin.file:
    path: "{{ redis_keyring_path }}"
    mode: '0644'
    owner: root
    group: root
    state: file
  become: true

- name: Redis | Remove legacy repository file (pre-rename)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pul_redis.list
    state: absent
  become: true

- name: Redis | Add Redis Labs repository
  ansible.builtin.apt_repository:
    repo: "{{ redis_apt_repository }}"
    state: present
    filename: redis
    update_cache: true

- name: Redis | install redis packages
  ansible.builtin.apt:
    name: "{{ redis_packages }}"
    state: present

- name: Redis | configure redis
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify:
    - restart redis

- name: Redis | ulimit value for redis
  ansible.builtin.template:
    src: redis_ulimit.conf.j2
    dest: /etc/security/limits.d/redis.conf
    mode: '0644'

- name: Redis | Set vm.overcommit
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: 1
    sysctl_file: /etc/sysctl.d/30-redis.conf
  when: redis__overcommit_memory_enable | bool

- name: Redis | ensure Redis Server service enabled
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
  when: running_on_server
