http:
  routers:
    metrics:
      rule: PathPrefix(`/metrics`)
      service: prometheus@internal
      entryPoints:
        - metrics
      middlewares:
        - metricAuth

    protected-sites:
      rule: "Header(`X-Forwarded-Host`, `catalog.princeton.edu`) || Header(`X-Forwarded-Host`, `datacommons.princeton.edu`) || Header(`X-Forwarded-Host`, `dpul.princeton.edu`) || Header(`X-Forwarded-Host`, `dss.princeton.edu`) || Header(`X-Forwarded-Host`, `figgy.princeton.edu`) || Header(`X-Forwarded-Host`, `findingaids.princeton.edu`) || Header(`X-Forwarded-Host`, `findingaids-qa.princeton.edu`) || Header(`X-Forwarded-Host`, `lae.princeton.edu`) || Header(`X-Forwarded-Host`, `maps.princeton.edu`)"
      entrypoints:
        - http

    # Skip the bot wall on ajax requests.
    skip-bot-wall:
      rule: "Header(`Sec-Fetch-Dest`, `empty`)"
      parentRefs:
        - protected-sites

    apply-bot-wall:
      rule: "!Header(`Sec-Fetch-Dest`, `empty`)"
      middlewares:
        - captcha-protect
      parentRefs:
        - protected-sites

    catalog-production:
      service: catalog-production
      rule: "Header(`X-Forwarded-Host`, `catalog.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    datacommons-production:
      service: datacommons-production
      rule: "Header(`X-Forwarded-Host`, `datacommons.princeton.edu`)"
      middlewares:
        - append-discovery-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    dpul-production:
      service: dpul-production
      rule: "Header(`X-Forwarded-Host`, `dpul.princeton.edu`)"
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    dss-production:
      service: dss-production
      rule: "Header(`X-Forwarded-Host`, `dss.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    figgy-production:
      service: figgy-production
      rule: "Header(`X-Forwarded-Host`, `figgy.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    findingaids-production:
      service: findingaids-production
      rule: "Header(`X-Forwarded-Host`, `findingaids.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    findingaids-qa:
      service: findingaids-qa
      rule: "Header(`X-Forwarded-Host`, `findingaids-qa.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    lae-production:
      service: lae-production
      rule: "Header(`X-Forwarded-Host`, `lae.princeton.edu`)"
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

    maps-production:
      service: maps-production
      rule: "Header(`X-Forwarded-Host`, `maps.princeton.edu`)"
      middlewares:
        - append-catalog-regex
      parentRefs:
        - apply-bot-wall
        - skip-bot-wall

  services:
    catalog-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://catalog1.princeton.edu:80
          - url: http://catalog2.princeton.edu:80
          - url: http://catalog3.princeton.edu:80
          - url: http://catalog4.princeton.edu:80
          - url: http://catalog5.princeton.edu:80
    datacommons-production:
      loadBalancer:
        healthCheck:
          path: /discovery/health.json
          timeout: 10
        servers:
          # Only discovery machines are being routed to traefik so only discovery machines are needed here
          - url: http://pdc-discovery-prod1.princeton.edu:80
          - url: http://pdc-discovery-prod2.princeton.edu:80
    dpul-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://dpul-prod1.princeton.edu:80
          - url: http://dpul-prod2.princeton.edu:80
    dss-production:
      loadBalancer:
        servers:
          - url: http://dss-prod1.princeton.edu:80
          - url: http://dss-prod2.princeton.edu:80
    figgy-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://figgy-web-prod1.princeton.edu:80
          - url: http://figgy-web-prod2.princeton.edu:80
          - url: http://figgy-web-prod3.princeton.edu:80
          - url: http://figgy-web-prod4.princeton.edu:80
    findingaids-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://pulfalight-jammy-prod1.princeton.edu:80
          - url: http://pulfalight-jammy-prod2.princeton.edu:80
    findingaids-qa:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://pulfalight-qa-web1.princeton.edu:80
    lae-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://lae-prod1.princeton.edu:80
          - url: http://lae-prod2.princeton.edu:80
    maps-production:
      loadBalancer:
        healthCheck:
          path: /health.json
          timeout: 10
        servers:
          - url: http://maps-prod1.princeton.edu:80
          - url: http://maps-prod2.princeton.edu:80
