---
microk8s_snap_channel: "1.35/stable"

# Use the external Helm provisioner role instead of MicroK8s' community NFS addon.
microk8s_enable_nfs_addon: false

microk8s_primary_node: k8s-staging1.lib.princeton.edu

microk8s_control_plane_nodes:
  - k8s-staging1.lib.princeton.edu
  - k8s-staging2.lib.princeton.edu
  - k8s-staging3.lib.princeton.edu

microk8s_worker_nodes:
  - k8s-staging4.lib.princeton.edu

microk8s_cluster_nodes: "{{ microk8s_control_plane_nodes + microk8s_worker_nodes }}"

microk8s_ingress_allowed_sources:
  - "172.20.80.13"
  - "172.20.80.14"

nfs_allowed_cidr: "172.20.80.0/24"
