---
galaxy_info:
  role_name: Pulmirror
  company: Princeton University Library
  description: manages our pulmirror
  author: pulibrary

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: FreeBSD
      versions:
        - all
dependencies:
  - role: nginx
