---
- name: Nginx | Install nginx on FreeBSD
  community.general.pkgng:
    name: "{{ nginx_package_name }}"
    state: present

- name: Nginx | Enable nginx in rc.conf
  community.general.sysrc:
    name: nginx_enable
    value: "YES"
  when: nginx_enable_service
