---
# tasks file for roles/nginx
- name: Nginx | Include Ubuntu tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Nginx | Include FreeBSD tasks
  ansible.builtin.include_tasks: freebsd.yml
  when: ansible_os_family == "FreeBSD"

- name: Nginx | Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Nginx | Include service tasks
  ansible.builtin.include_tasks: service.yml
