---
- name: Nginx | Ensure nginx is enabled and running
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    enabled: "{{ nginx_enable_service }}"
    state: "{{ 'started' if nginx_start_service else 'stopped' }}"
  when: running_on_server
