---
entraid_join_domain: princeton.edu
entraid_join_client_id: "{{ vault_entraid_client_id }}"
entraid_join_client_secret: "{{ vault_entraid_himmelblau_client_secret }}"
entraid_join_pam_allow_groups:
  - "{{ vault_entraid_pam_allow_group_id }}"
