---
alma_read_write_key: "{{ vault_alma_sandbox_read_write_key }}"
install_mailcatcher: true
mailcatcher_user: "mailcatcher"
mailcatcher_group: "mailcatcher"
mailcatcher_version: 0.10.0
mailcatcher_home: /var/lib/mailcatcher
mailcatcher_install_location: /usr/local/bin/mailcatcher
ol_smtp_host: 'localhost'
ol_smtp_port: 1025
ol_bibdata_base: 'https://bibdata-staging.lib.princeton.edu'
ol_db_name: "{{ vault_ol_dedupe_db_name }}"
ol_db_user: "{{ vault_ol_dedupe_db_user}}"
ol_db_password: "{{ vault_ol_dedupe_db_password }}"
ol_graph_api_url: "{{ vault_ol_staging_graph_api_url }}"
ol_host_name: "catalog-dedupe.princeton.edu"
ol_rabbit_host: "{{ figgy_staging_rabbit_host }}"
ol_rabbit_password: "{{ vault_rabbit_staging_password }}"
ol_rabbit_user: "{{ vault_rabbit_staging_user }}"
ol_read_only_mode: 'false'
central_redis_host: 'lib-redis-staging1.princeton.edu'
central_redis_db: '9'
ol_secret_key: "{{ vault_ol_dedupe_secret_key }}"
ol_secret_key_base: "{{ vault_ol_dedupe_secret_key_base }}"
passenger_app_env: "dedupe"
passenger_server_name: "catalog-dedupe.*"
postgres_admin_user: "postgres"
postgres_host: "lib-postgres-staging1.princeton.edu"
rails_app_env: "dedupe"
passenger_max_pool_size: 8
scsb_auth_key: "{{ vault_scsb_auth_key }}"
