---
signoz_ingress_enabled: true
signoz_ingress_host: signoz-staging.lib.princeton.edu
signoz_ingress_class_name: public

signoz_global_storage_class: k8s-fs-nfs

signoz_clickhouse_local_storage_enabled: true
signoz_clickhouse_local_storage_class: clickhouse-local
signoz_clickhouse_local_pv_name: clickhouse-signoz-local-pv
signoz_clickhouse_local_pv_size: 450Gi
signoz_clickhouse_local_mount_path: /var/lib/clickhouse
signoz_clickhouse_local_pv_path: /var/lib/clickhouse/pv-signoz
signoz_clickhouse_local_pv_owner: "101"
signoz_clickhouse_local_pv_group: "101"
signoz_clickhouse_local_pv_mode: "0750"
signoz_clickhouse_local_storage_node: k8s-staging4.lib.princeton.edu
signoz_clickhouse_chi_name: signoz-clickhouse
