---
imagecat_secret_key_base: '{{vault_imagecat_production_secret_key}}'
db_name: 'imagecat_rails_prod'
db_user: 'imagecat_rails_prod'
db_password: '{{ vault_imagecat_production_db_password }}'
db_host: 'lib-postgres-prod1.princeton.edu'
db_admin_user: "postgres"
database_connections:
  - db_host: '{{ db_host }}'
    db_name: '{{ db_name }}'
    db_user: '{{ db_user }}'
    db_owner: '{{ db_user }}'
    db_password: '{{ db_password }}'
    db_admin_user: "{{ db_admin_user }}"
nomad_vars:
  imagecat-production:
    SECRET_KEY_BASE: '{{ imagecat_secret_key_base }}'
    DB_NAME: '{{ db_name }}'
    DB_USER: '{{ db_user }}'
    DB_PASSWORD: '{{ db_password }}'
    POSTGRES_HOST: '{{ db_host }}'
    AWS_ACCESS_KEY_ID: '{{ vault_imagecat_production_aws_access_key_id }}'
    AWS_SECRET_ACCESS_KEY: '{{ vault_imagecat_production_aws_secret_access_key }}'
