#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/k8s_nfs
nfsserver_packages: nfs-kernel-server
nfsserver_services: nfs-kernel-server
nfs_export_root: /var/nfs
nfs_export_path: /var/nfs/k8s
nfs_export_owner: root
nfs_export_group: root
nfs_export_mode: "0755"

nfs_export_allowed_clients: "172.20.80.0/24"

nfs_export_options:
  - rw
  - sync
  - no_subtree_check
  - no_root_squash
