---
# Install a nagios core server on Ubuntu 22.04 LTS Jammy Jellyfish
#
# might need to sudo apt-get -y install python-simplejson

    - name: update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: install aptitude
      become: true
      ansible.builtin.apt:
        name: aptitude
        state: present

    - name: upgrade apt packages
      become: true
      ansible.builtin.apt: upgrade=full

    - name: install packages for nagios
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - build-essential
        - curl
        - libapache2-mod-php
        - libc6-dev
        - libssl-dev
        - openssl
        # we do this later? - python-passlib
        - unzip

    - name: create nagcmd group
      become: true
      group: name=nagcmd state=present

    - name: set perms on /opt
      become: true
      file:
        name: /opt/install
        state: directory
        owner: pulsys
        group: pulsys

    - name: add nagios and apache users to nagcmd group
      become: true
      user: name={{ item }} groups=nagcmd state=present
      with_items:
        - nagios
        - www-data

    - name: download nagios source
      get_url: url=http://downloads.sourceforge.net/project/nagios/nagios-4.x/nagios-{{ nagios_core_version }}/nagios-{{ nagios_core_version }}.tar.gz dest={{ install_path }}/nagios-{{ nagios_core_version }}.tar.gz

    - name: unzip nagios core source
      unarchive: src={{ install_path }}/nagios-{{ nagios_core_version }}.tar.gz dest={{ install_path }}/ creates={{ install_path }}/nagios-{{ nagios_core_version }}/compile.c copy=no

    - name: configure nagios core
      shell: cd {{ install_path }}/nagios-{{ nagios_core_version }} && ./configure --disable-shared creates={{ install_path }}/nagios-{{ nagios_core_version }}/Makefile

    - name: make and install nagios core
    # this is NOT idempotent
      become: true
      shell: cd {{ install_path }}/nagios-{{ nagios_core_version }} && make {{ item }}
      with_items:
        - all
        - install
        - install-init
        - install-config
        - install-commandmode
        - install-webconf

    - name: install python-passlib
      become: true
      ansible.builtin.apt:
        name: python-passlib
        state: present

    - name: set admin password
      become: true
      htpasswd:
        path: /usr/local/nagios/etc/htpasswd.users
        name: nagiosadmin
        password: "{{ nagios_admin_password }}"
        crypt_scheme: des_crypt
        state: present

    - name: disable mpm_event module
      become: true
      apache2_module:
        state: absent
        name: mpm_event
        # ignore_configcheck: True

    - name: enable correct apache modules
      become: true
      apache2_module:
        state: present
        name: "{{ item }}"
      with_items:
        - mpm_prefork
        - php7.0
        - cgi

    - name: install nagios service definition
      become: true
      copy:
        src: new-nagios-service
        dest: /etc/systemd/system/nagios.service

    - name: enable nagios service
      become: true
      ansible.builtin.service:
        name: nagios
        enabled: true

    - name: restart apache and nagios
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
          - nagios
          - apache2

    - name: install ncpa and nagios plugins
      include_tasks: ncpa.yml
