---
# handlers file for postgresql
- name: Reload remote postgres
  ansible.builtin.systemd:
    name: postgresql
    # the service name on RHEL/Rocky is different
    # but we shouldn't need that here
    state: reloaded
  become: yes
  delegate_to: '{{ postgres_host }}'
