---
# handlers/main.yml
#

- name: Reload step-ca
  ansible.builtin.systemd_service:
    name: step-ca
    state: reloaded

- name: Restart step-ca
  ansible.builtin.systemd_service:
    name: step-ca
    state: restarted
    daemon_reload: true
