---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:1.0

dependencies:
  ansible_core:
    package_pip: ansible-core==2.19.4

  ansible_runner:
    package_pip: ansible-runner

  python_interpreter:
    # The base image defaults to Python 3.9, so install and use 3.11.
    package_system: python3.11
    python_path: /usr/bin/python3.11

  galaxy:
    collections:
      - name: checkmk.general
        version: 6.4.1

      - name: paloaltonetworks.panos
        version: 3.2.0

      - name: servicenow.servicenow
        version: 1.0.6

      - name: community.proxmox
        version: 2.0.0

  python:
    - ansible==12.2.0
    - six
    - psutil
    - requests
    - google-auth
    - proxmoxer>=2.3,<3

  system:
    - git
    - python3-dnf
    - python3.11-pip
    - python3.11-devel

options:
  package_manager_path: /usr/bin/microdnf
