---
galaxy_info:
  role_name: loadtest
  company: Princeton University Library
  description: Installs Apache JMeter and Grafana k6 for load testing
  author: pulibrary

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
