---
galaxy_info:
  role_name: fleet_mysql
  company: Princeton University Library
  description: Oracle MySQL server role for applications that cannot run on MariaDB
  author: pulibrary

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies:
  - role: "common"
