#!/bin/bash

set -e

ancestor_version=$1
current_version=$2
other_version=$3
conflict_marker_size=$4
merged_result_pathname=$5

ancestor_tempfile=$(mktemp tmp.XXXXXXXXXX)
current_tempfile=$(mktemp tmp.XXXXXXXXXX)
other_tempfile=$(mktemp tmp.XXXXXXXXXX)

delete_tempfiles() {
    rm -f "$ancestor_tempfile" "$current_tempfile" "$other_tempfile"
}
trap delete_tempfiles EXIT

ansible-vault decrypt --output "$ancestor_tempfile" "$ancestor_version"
ansible-vault decrypt --output "$current_tempfile" "$current_version"
ansible-vault decrypt --output "$other_tempfile" "$other_version"

git merge-file "$current_tempfile" "$ancestor_tempfile" "$other_tempfile"

ansible-vault encrypt --output "$current_version" "$current_tempfile"
^D
