packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    vmware = {
      source  = "github.com/hashicorp/vmware"
      version = "~> 1"
    }
  }
}

source "vmware-iso" "autogenerated_1" {
  boot_command      = ["<esc><wait>", "linux ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter>"]
  communicator      = "ssh"
  cpus              = 2
  disk_size         = 30720
  guest_os_type     = "centos8-64"
  http_directory    = "http"
  iso_checksum      = "sha256:ee3ac97fdffab58652421941599902012179c37535aece76824673105169c4a2"
  iso_url           = "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.4-x86_64-minimal.iso"
  memory            = 8192
  shutdown_command  = "echo 'packer' | sudo -S shutdown -P now"
  ssh_password      = "packer"
  ssh_username      = "packer"
  ssh_wait_timeout  = "20m"
  vm_name           = "lib-vm"
  vmx_data = {
    "cpuid.coresPerSocket"                 = "1"
    "ethernet0.addressType"                = "generated"
    "ethernet0.connectable.startConnected" = "TRUE"
    "ethernet0.networkName"                = "VM Network"
    "ethernet0.present"                    = "TRUE"
    "ethernet0.virtualDev"                 = "vmxnet3"
    guestOS                                = "centos8-64"
    memsize                                = "8192"
    numvcpus                               = "2"
    "scsi0.present"                        = "TRUE"
    "scsi0.virtualDev"                     = "lsilogic"
    "scsi0:0.deviceType"                   = "scsi-hardDisk"
    "scsi0:0.fileName"                     = "rocky-linux.vmdk"
    "scsi0:0.present"                      = "TRUE"
  }
}

build {
  sources = ["source.vmware-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["echo 'packer ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers", "dnf install -y ansible"]
  }

  provisioner "ansible" {
    playbook_file = "playbooks/pul_image.yml"
  }

}
