packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    vmware = {
      source  = "github.com/hashicorp/vmware"
      version = "~> 1"
    }
  }
}

source "vmware-iso" "autogenerated_1" {
  boot_command      = ["<esc><wait>", "<esc><wait>", "<enter><wait>", "/install/vmlinuz<wait>", " auto<wait>", " console-setup/ask_detect=false<wait>", " console-setup/layoutcode=us<wait>", " console-setup/modelcode=pc105<wait>", " debconf/frontend=noninteractive<wait>", " debian-installer=en_US<wait>", " fb=false<wait>", " initrd=/install/initrd.gz<wait>", " kbd-chooser/method=us<wait>", " keyboard-configuration/layout=USA<wait>", " keyboard-configuration/variant=USA<wait>", " locale=en_US<wait>", " netcfg/get_domain=vm<wait>", " netcfg/get_hostname=ubuntu<wait>", " grub-installer/bootdev=/dev/sda<wait>", " noapic<wait>", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>", " -- <wait>", "<enter><wait>"]
  communicator      = "ssh"
  cpus              = 2
  disk_size         = 30720
  guest_os_type     = "ubuntu64Guest"
  http_directory    = "http"
  iso_checksum      = "sha256:45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2"
  iso_url           = "https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso"
  memory            = 8192
  shutdown_command  = "echo 'packer' | sudo -S shutdown -P now"
  ssh_password      = "packer"
  ssh_username      = "packer"
  ssh_wait_timeout  = "20m"
  vm_name           = "lib-vm"
  vmx_data = {
    "cpuid.coresPerSocket"                 = "1"
    "ethernet0.addressType"                = "generated"
    "ethernet0.connectable.startConnected" = "TRUE"
    "ethernet0.networkName"                = "VM Network"
    "ethernet0.present"                    = "TRUE"
    "ethernet0.virtualDev"                 = "vmxnet3"
    guestOS                                = "ubuntu-64"
    "ide1:0.deviceType"                    = "cdrom-image"
    "ide1:0.fileName"                      = "ubuntu-20.04.4-live-server-amd64.iso"
    "ide1:0.present"                       = "TRUE"
    memsize                                = "8192"
    numvcpus                               = "2"
    "scsi0.present"                        = "TRUE"
    "scsi0.virtualDev"                     = "lsilogic"
    "scsi0:0.deviceType"                   = "scsi-hardDisk"
    "scsi0:0.fileName"                     = "ubuntu.vmdk"
    "scsi0:0.present"                      = "TRUE"
  }
}

build {
  sources = ["source.vmware-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["echo 'packer ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers", "apt-get update"]
  }

  provisioner "ansible" {
    playbook_file = "playbooks/pul_image.yml"
  }

}
