---
- name: Firewall | Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
  listen: Reload sysctl

- name: Firewall | Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  listen: Restart fail2ban
