---
- name: Nfsserver | add conan group
  ansible.builtin.group:
    name: "conan"
    gid: 1002
    state: present

- name: Nfsserver | create system user
  ansible.builtin.user:
    name: "conan"
    uid: 1002
    group: "conan"
    home: "/home/conan"
    shell: "/usr/bin/bash"
