---
dspace_version: 6.3
tomcat8_enabled: true
tomcat8_hostname: localhost
tomcat8_server_port: 8005
tomcat8_catalina_port: 8983
tomcat8_catalina_redirect_port: 8443
tomcat_shutdown_port: "{{ tomcat8_server_port }}"
tomcat_port: 8080
tomcat_connection_timeout: 20000
tomcat_redirect_port: "{{ tomcat8_catalina_redirect_port }}"
tomcat_ajp_port: 8009
dspace_source: "/opt/dspace-{{ dspace_version }}-release"
dspace_home: /dspace
dspace_db: dspace
# dspace_db_host: "{{ vault_dspace_db_host }}"
dspace_db_host: localhost
dspace_db_user: dspace
# dspace_db_password: "{{ vault_dspace_db_password }}"
dspace_db_password: dspace
dspace_solr_url: http://localhost:8080/solr
dspace_site_name: DSpace at My University
dspace_host_name: localhost
dspace_base_url: http://localhost:8080
