---
# vars file for roles/loadtest
loadtest_arch_map:
  x86_64: amd64
  aarch64: arm64
loadtest_k6_arch: "{{ loadtest_arch_map[ansible_facts['architecture']] }}"
loadtest_k6_name: "k6-v{{ loadtest_k6_version }}-linux-{{ loadtest_k6_arch }}"
loadtest_k6_url: "https://github.com/grafana/k6/releases/download/v{{ loadtest_k6_version }}/{{ loadtest_k6_name }}.tar.gz"
