---
galaxy_info:
  role_name: lib_sftp
  company: Princeton University Library
  description: sftp server
  author: pulibrary

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: EL
      versions:
        - "9"
dependencies:
  - role: "ssh_ca_trust"
  - role: "deploy_user"
