#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/openresty
openresty_package: openresty
openresty_node_package: node

openresty_user: altcha
openresty_group: altcha
openresty_altcha_home: /opt/altcha-server

openresty_secret: "{{ vault_openresty_altcha_secret }}"
openresty_altcha_port: 8787

openresty_server_name: "_"
openresty_listen_port: 80

openresty_upstream: "http://127.0.0.1:3000"

openresty_altcha_cookie_name: "altcha_verified"
openresty_altcha_cookie_ttl: 3600

openresty_protected_locations:
  - /

openresty_ssl_cert_dir: /var/db/lego/certificates
openresty_ssl_key_dir:  /var/db/lego/certificates
