# Ansible managed
# In this file are TCP upstreams for load balancing services that are hosted in
# Nomad, but apps outside of Nomad need to access them.
upstream figgy-rabbitmq-staging {
    resolver nomad-host-prod1.lib.princeton.edu:8600 nomad-host-prod2.lib.princeton.edu:8600 nomad-host-prod3.lib.princeton.edu:8600 valid=5s ipv6=off;
    resolver_timeout 2s;
    zone figgy-rabbitmq-staging 64k;
    server service.consul service=rabbitmq-staging resolve max_fails=0;
}

# Figgy RabbitMQ Staging - proxies for a cluster.
server {
    listen 10000;
    proxy_pass figgy-rabbitmq-staging;
    proxy_connect_timeout 3s;
    proxy_timeout 1h;
    include /etc/nginx/conf.d/templates/restrict.conf;
    deny all;
}

upstream figgy-rabbitmq-production {
    resolver nomad-host-prod1.lib.princeton.edu:8600 nomad-host-prod2.lib.princeton.edu:8600 nomad-host-prod3.lib.princeton.edu:8600 valid=5s ipv6=off;
    resolver_timeout 2s;
    zone figgy-rabbitmq-production 64k;
    server service.consul service=rabbitmq-production resolve max_fails=0;
}

# Figgy RabbitMQ Production - proxies for a cluster.
server {
    listen 10001;
    proxy_pass figgy-rabbitmq-production;
    proxy_connect_timeout 3s;
    proxy_timeout 1h;
    include /etc/nginx/conf.d/templates/restrict.conf;
    deny all;
}

upstream figgy-memcached-staging {
    resolver nomad-host-prod1.lib.princeton.edu:8600 nomad-host-prod2.lib.princeton.edu:8600 nomad-host-prod3.lib.princeton.edu:8600 valid=5s ipv6=off;
    resolver_timeout 2s;
    zone figgy-rabbitmq-production 64k;
    server service.consul service=figgy-infrastructure-staging-memcached resolve max_fails=0;
}

# Figgy Memcached Staging - proxies for a cluster.
server {
    listen 10002;
    proxy_pass figgy-memcached-staging;
    proxy_connect_timeout 3s;
    proxy_timeout 1h;
    include /etc/nginx/conf.d/templates/restrict.conf;
    deny all;
}
