# Ansible managed
upstream figgy-rabbitmq-staging {
    resolver nomad-host-prod1.lib.princeton.edu:8600 nomad-host-prod2.lib.princeton.edu:8600 nomad-host-prod3.lib.princeton.edu:8600 valid=5s ipv6=off;
    resolver_timeout 2s;
    zone figgy-rabbitmq-staging 64k;
    server service.consul service=rabbitmq-staging resolve max_fails=0;
    keepalive 0;
}

# Figgy RabbitMQ Staging - proxies for a cluster.
server {
    listen 10000;
    proxy_pass figgy-rabbitmq-staging;
    proxy_connect_timeout 3s;
    proxy_timeout 1h;
    include /etc/nginx/conf.d/templates/restrict.conf;
    deny all;
}
