---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: check bibdata software status
    package:
      name: "{{ item }}"
      state: present
    check_mode: true
    register: pkg_status
    loop:
      - cifs-utils
      - python3-psycopg2

  - name: test for bibdata software packages
    assert:
      that:
        - not pkg_status.changed

  - name: Check if bibdata mount directory exists when running_on_server is true
    ansible.builtin.stat:
     path: "{{ bibdata_data_dir | default('/data/bibdata_files') }}"
    register: bibdata_mount_stat

  - name: Assert that bibdata mount directory exists
    ansible.builtin.assert:
      that:
        - bibdata_mount_stat.stat.exists
        - bibdata_mount_stat.stat.isdir
      fail_msg: "Mount directory {{ bibdata_data_dir | default('/data/bibdata_files') }} does not exist"
