---
- name: mailcatcher | creating mailcatcher group
  group:
    name: "mailcatcher"

- name: mailcatcher | creating mailcatcher user
  user:
    name: "mailcatcher"
    comment: "Mailcatcher Service Account"
    group: "mailcatcher"
