---
- name: Mailcatcher | Install requested gem version
  ansible.builtin.command:
    argv:
      - gem
      - install
      - mailcatcher
      - --version
      - "{{ mailcatcher_version }}"
      - --no-document
      - --bindir
      - "{{ mailcatcher_install_location | dirname }}"
    creates: "{{ mailcatcher_install_location }}"
