---
# tasks file for roles/mailcatcher
- name: mailcatcher | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items: '{{ mailcatcher_ubuntu_packages }}'

- import_tasks: create_user.yml
- import_tasks: install.yml
- import_tasks: config.yml

- name: mailcatcher | daemon-reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: mailcatcher | restart mailcatcher
  ansible.builtin.systemd:
    name: mailcatcher
    state: restarted
    enabled: yes
