# Ansible managed
server {
    listen 80;
    server_name getit.princeton.edu;

    location / {
        return 301 https://$server_name$request_uri;
    }

}

    server {
        listen 443 ssl;
        server_name getit.princeton.edu;

        rewrite ^/resolve(.*)$ https://princeton.alma.exlibrisgroup.com/discovery/openurl?institution=01PRI_INST&vid=01PRI_INST:Services&$1 permanent;
        rewrite ^/(.*)$ https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=Online&f%5Bformat%5D%5B%5D=Journal permanent;

        ssl_certificate            /etc/letsencrypt/live/getit/fullchain.pem;
        ssl_certificate_key        /etc/letsencrypt/live/getit/privkey.pem;
        ssl_session_cache          shared:SSL:1m;
        ssl_prefer_server_ciphers  on;

    }