# Ansible managed
proxy_cache_path /var/cache/nginx/oawaiver-prod/ keys_zone=oawaiver-prodcache:10m;

server {
    listen 80;
    server_name oawaiver.princeton.edu;

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name oawaiver.princeton.edu;

    ssl_certificate            /etc/letsencrypt/live/oawaiver/fullchain.pem;
    ssl_certificate_key        /etc/letsencrypt/live/oawaiver/privkey.pem;
    ssl_session_cache          shared:SSL:1m;
    ssl_prefer_server_ciphers  on;

    location / {
        return 301 https://library.princeton.edu/services/scholarly-communications/faculty-open-access-policy;
    }

    include /etc/nginx/conf.d/templates/errors.conf;
}
