---
galaxy_info:
  role_name: rails_app
  company: Princeton University Library
  description: Rails App Role
  author: pulibrary

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: 'common'
  - role: 'bind9'
  - role: 'deploy_user'
  - role: 'passenger'
  # disabling the postgresql role for psql-client test
  # we're using Approvals to test, and the Approvals role already calls psql-client
  # - role: postgresql
  #   tags: 'postgresql'
  - role: nodejs
    when: install_nodejs|default(true)
