---
galaxy_info:
  role_name: rails_app
  company: Princeton University Library
  description: Rails App Role
  author: pulibrary

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: 'common'
  - role: 'bind9'
  - role: 'deploy_user'
  - role: 'passenger'
  # switching from the postgresql role to the psql-client role
  # as part of using Approvals to test the new role
  # the Approvals role now relies on this role to call psql-client
  # - role: postgresql
  #   tags: 'postgresql'
  - role: psql-client
  - role: nodejs
    when: install_nodejs|default(true)
