---
# defaults file for dss
running_on_server: true
dss_db_name: "dss_staging"
dss_db_password: "{{ dssdb_password | default('change_this') }}"
dss_db_user: "dss"
maria_db_name: "dss_staging"
maria_db_user: "dss"
solr_url: "http://lib-solr8-prod.princeton.edu:8983/solr/dss"
dss_honeybadger_key: change_me
install_mailcatcher: false
# postgres test VM settings
postgres_port: 5432
postgres_version: 15
postgres_host: postgres
postgres_admin_user: postgres
vault_postgres_admin_password: postgres
postgres_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
