---
- name: Converge
  hosts: all
  vars:
    running_on_server: false
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
  tasks:
    - name: "Include roles/apache2"
      include_role:
        name: "apache2"
