# ANSIBLE MANAGED
# Please make changes in the princeton_ansible repository

pool pool.ntp.org iburst minpoll 8 maxpoll 9

{% if ansible_os_family == "Debian" %}
confdir /etc/chrony/conf.d
sourcedir /run/chrony-dhcp
sourcedir /etc/chrony/sources.d
driftfile /var/lib/chrony/chrony.drift
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony
{% elif ansible_os_family == "FreeBSD" %}
sourcedir /usr/local/etc/sources.d
driftfile /var/db/chrony/chrony.drift
logdir /var/log
{% else %}
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
{% endif %}

keyfile {{ chrony_keyfile }}

maxupdateskew 100.0
rtcsync
makestep 1 3

{% if ansible_os_family != "FreeBSD" %}
leapsectz right/UTC
{% endif %}
