#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/beyla
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart beyla
  ansible.builtin.systemd:
    name: beyla
    state: restarted
