#!/bin/sh

#
# chkconfig: 345 99 00
# description: Starts and stop the EZproxy daemon
#
# To run EZproxy as non-root, change the line(s) that end $* to be like:
#    su - someuser -c "/var/local/ezproxy/ezproxy $*"
#

if [ -z "$1" ]
then
  echo "Usage: $0 {start|stop|restart|bounce|status}"
  exit 1
fi

/var/local/ezproxy/ezproxy $*
