---
- name: Elastic | install APT transport for Elasticsearch repository.
  apt:
    name: apt-transport-https
    state: present

- name: Elastic | Modify hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: running_on_server

- name: Elastic | install specific version of Elastic
  apt:
    deb: "{{ elastic_download_url }}/elasticsearch-oss-{{ elasticsearch_version }}-amd64.deb"

- name: Elastic | Pre-installation flight check
  stat:
    path: /etc/elasticsearch
  register: elastic_conf_dir

- name: Elastic | disable elastic
  service:
    enabled: false
    masked: true
    name: elasticsearch
  when: elastic_conf_dir is not defined

- include_tasks: configure.yml
- include_tasks: post_configuration.yml

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
