---
galaxy_info:
  role_name: rocky_mirror
  company: Princeton University Library
  description: Rocky Linux mirror via rsync
  author: pulibrary
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: FreeBSD
      versions:
        - "15"
dependencies:
  - role: pulmirror
