---
# vars file for roles/pulibrary.opendistro
elastic_url: "artifacts.elastic.co"
__opendistroforelasticsearch_user: elasticsearch
__opendistroforelasticsearch_group: elasticsearch
__opendistroforelasticsearch_log_dir: /var/log/elasticsearch
__opendistroforelasticsearch_db_dir: /var/lib/elasticsearch
__opendistroforelasticsearch_package: opendistroforelasticsearch
__opendistroforelasticsearch_conf_dir: /etc/elasticsearch
__opendistroforelasticsearch_scripts_dir: ""
__opendistroforelasticsearch_plugins_dir: /usr/share/elasticsearch/plugins
__opendistroforelasticsearch_plugin_command: /usr/share/elasticsearch/bin/elasticsearch-plugin
__opendistroforelasticsearch_service: elasticsearch
__opendistroforelasticsearch_java_home: ""
apt_repo_keys_to_add:
  - https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
opendistroforelasticsearch_flags: |
  ES_PATH_CONF={{ opendistroforelasticsearch_conf_dir }}
  ES_STARTUP_SLEEP_TIME=5
  MAX_OPEN_FILES=65535
  MAX_LOCKED_MEMORY=unlimited
