---
step_ca_ssh_principals:
  - ac2754
  - ar1789
  - gpmenos
  - jkazmier
  - kayiwa
  - vk4273

step_ca_oidc_enabled: true

step_ca_oidc_admins:
  - ac2754@princeton.edu
  - ar1789@princeton.edu
  - gpmenos@princeton.edu
  - jkazmier@princeton.edu
  - kayiwa@princeton.edu
  - fkayiwa@princeton.edu
  - vk4273@princeton.edu


step_ca_oidc_listen_address: "localhost:10000"

step_ca_password: "{{ vault_step_ca_password }}"
step_ca_oidc_tenant_id: "2ff60116-7431-425d-b5af-077d7791bda4"
step_ca_oidc_client_id: "{{ vault_step_ca_oidc_client_id }}"
step_ca_oidc_client_secret: "{{ vault_step_ca_oidc_client_secret }}"

# principal users
ssh_ca_operator_group: opsys
ssh_ca_manage_operator_sudo: true
ssh_ca_users:
  - { name: ac2754, principals: [ac2754@princeton.edu] }
  - { name: ar1789, principals: [ar1789@princeton.edu] }
  - { name: gpmenos, principals: [gpmenos@princeton.edu] }
  - { name: jkazmier, principals: [jkazmier@princeton.edu] }
  - { name: kayiwa, principals: [kayiwa@princeton.edu] }
  - { name: vk4273, principals: [vk4273@princeton.edu] }
