---
# tasks file for pulibrary-nomad-node
- name: 'nomad-node | Install Podman'
  ansible.builtin.apt:
    name: "podman"
    state: present
    update_cache: true
- name: 'nomad-node | Keep Podman Up'
  ansible.builtin.service:
    name: "podman"
    state: "started"
    enabled: true
- name: 'nomad-node | Install consul'
  ansible.builtin.include_role:
    name: 'ansible-consul'
    public: true
- name: Print the main token
  ansible.builtin.debug:
    msg: "Test: {{ consul_acl_replication_token }}"
- name: 'nomad-node | Install nomad'
  ansible.builtin.include_role:
    name: 'ansible-nomad'
