FROM pulibrary/puldocker-ubuntu1804-ansible:latest

# Install postgres
RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql

# Ensure postgres service is running
RUN service postgresql restart
CMD ["/sbin/my_init"]