---
# defaults file for roles/xrdp
#
# The RDP port is opened by the firewall role, which this role depends on. See
# firewall_allow_rdp and firewall_rdp_cidrs in roles/firewall/defaults/main.yml.
xrdp_port: 3389

xrdp_desktop: xfce

xrdp_packages_common:
  - dbus-x11
  - dbus-user-session
  - libpam-systemd
  - xorgxrdp
  - xrdp
# Xubuntu / XFCE
xrdp_packages_xfce:
  - xfce4
  - xfce4-goodies
  - xfce4-screensaver
  - xfce4-session
  - xfce4-terminal
  - xfconf
