---
- name: Entraid_join | Ensure passwd uses himmelblau NSS
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd:'
    line: 'passwd:     files himmelblau systemd'
    backup: true
  notify:
    - restart himmelblaud

- name: Entraid_join | Ensure group uses himmelblau NSS
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group:'
    line: 'group:      files himmelblau systemd'
    backup: true
  notify:
    - restart himmelblaud
