---
- name: Entraid_join | Configure Ubuntu common-auth for Himmelblau MFA
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-auth
    regexp: '^auth\s+.*pam_himmelblau\.so.*'
    line: 'auth     [success=2 default=ignore]    pam_himmelblau.so ignore_unknown_user mfa_poll_prompt no_hello_pin'
    backup: true
    firstmatch: true
  when: ansible_os_family == "Debian"
  notify:
    - restart himmelblaud

- name: Entraid_join | Remove duplicate Ubuntu sufficient pam_himmelblau auth line
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-auth
    regexp: '^auth\s+sufficient\s+pam_himmelblau\.so\s+ignore_unknown_user\s+mfa_poll_prompt\s+no_hello_pin'
    state: absent
    backup: true
  when: ansible_os_family == "Debian"
  notify:
    - restart himmelblaud

- name: Entraid_join | Configure Rocky system-auth for Himmelblau MFA
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth\s+sufficient\s+pam_himmelblau\.so.*'
    line: 'auth     sufficient      pam_himmelblau.so ignore_unknown_user mfa_poll_prompt no_hello_pin'
    backup: true
  when: ansible_os_family == "RedHat"
  notify:
    - restart himmelblaud

- name: Entraid_join | Configure Rocky password-auth for Himmelblau MFA
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: '^auth\s+sufficient\s+pam_himmelblau\.so.*'
    line: 'auth     sufficient      pam_himmelblau.so ignore_unknown_user mfa_poll_prompt no_hello_pin'
    backup: true
  when: ansible_os_family == "RedHat"
  notify:
    - restart himmelblaud
