---
- name: 'pul_nomad_reservoir | add the application environment variables'
  ansible.builtin.shell:
    cmd: '/usr/local/bin/nomad var put -force nomad/jobs/reservoir {{ reservoir_nomad_env_vars.keys() | zip(reservoir_nomad_env_vars.values()) | map("join", "=") | join(" ") }}'
  environment:
    NOMAD_TOKEN: '{{ pul_nomad_management_token }}'
  run_once: true