---
galaxy_info:
  role_name: Global Protect Update
  company: Princeton University Library
  description: GlobalProtect gateway IP resolver for nginx set_real_ip_from
  author: pulibrary

  license: MIT

  min_ansible_version: 2.14

  platforms:
    - name: FreeBSD
      versions:
        - ["15"]
dependencies: []
  # uncomment the line below and remove the `[]` above in your role
  # - role: "<role I depend on>"
