#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/signoz_k8s
signoz_namespace: platform
signoz_release_name: signoz
signoz_chart_repo_name: signoz
signoz_chart_repo_url: https://charts.signoz.io
signoz_chart_ref: signoz/signoz
signoz_chart_version: ""

signoz_storage_class: k8s-fs-nfs
signoz_service_type: NodePort
signoz_http_node_port: 32080

nfs_export_path: /var/nfs/k8s
nfs_export_allowed_clients: "172.20.80.0/24"
nfs_export_options:
  - rw
  - sync
  - no_subtree_check
  - no_root_squash

nfs_ufw_rules:
  - port: "2049"
    proto: tcp
    comment: "NFS"
  - port: "2049"
    proto: udp
    comment: "NFS UDP"
  - port: "111"
    proto: tcp
    comment: "rpcbind"
  - port: "111"
    proto: udp
    comment: "rpcbind UDP"
