---
# set vars for Ubuntu
postgres_client_packages:
  - libpq-dev
  - python3-psycopg2
  - postgresql-client-{{ postgres_version }}
postgres_conf_directory: "/etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}"
postgres_data_directory: "/var/lib/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}"
postgres_log_file: "/var/lib/postgresql/{{ postgres_version }}/main/pg_log/pg.json"
postgresql_log_path: "{{ postgres_log_file }}"
postgres_packages:
  - postgresql-{{ postgres_version }}
  - postgresql-client-{{ postgres_version }}
  - postgresql-contrib-{{ postgres_version }}
postgres_service_name: "postgresql"
