---
# set vars for RHEL
postgres_client_packages:
  - libpq-devel
  - python3-psycopg2
postgres_conf_directory: "{{ postgres_data_directory }}"
postgres_data_directory: /var/lib/pgsql/{{ postgres_version }}/data
postgres_log_file: /var/lib/pgsql/{{ postgres_version }}/data/pg_log/pg.csv
# ^^^ is the right path for PG16 on RHEL9
# but do we want .csv or .json?
postgresql_log_path: "{{ postgres_log_file }}"
postgres_packages: postgresql{{ postgres_version }}-server
postgres_service_name: postgresql-{{ postgres_version }}
