---
database_connections: []
nomad_volumes: []
# Some things build a container on push, for those cases provide BRANCH= and the
# repo to build a specific branch.
nomad_branch: "{{ lookup('ansible.builtin.env', 'BRANCH') | default('main', true) }}"
nomad_repository: "{{ lookup('ansible.builtin.env', 'REPO') | default('princeton_ansible', true) }}"
