---
- name: Bitcurator | disable power management for admin user
  ansible.builtin.copy:
    dest: "{{ admin_home }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0644"
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <channel name="xfce4-power-manager" version="1.0">
        <property name="xfce4-power-manager" type="empty">
          <property name="blank-on-ac" type="int" value="0"/>
          <property name="dpms-enabled" type="bool" value="false"/>
          <property name="dpms-on-ac-off" type="int" value="0"/>
          <property name="dpms-on-ac-sleep" type="int" value="0"/>
          <property name="logind-handle-lid-switch" type="bool" value="false"/>
        </property>
      </channel>
