---
- name: Bitcurator | create common mount points
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /mnt/data
    - /mnt/rbrr
    - /mnt/archives_bd
    - /mnt/raid
