- name: allsearch_frontend | Make sure shared application directory exists
  ansible.builtin.file:
    path: "{{ capistrano_base_dir }}/shared"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0755
- name: allsearch_frontend | Install .env in shared application directory
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ capistrano_base_dir }}/shared/.env"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0644
