---
# Based on:
# https://github.com/pulibrary/princeton_ansible/blob/main/roles/postgresql/tasks/create_users.yml
#
# Don't leave this task! Just seeing ifI can get the tests passing
- name: Install postgresql libraries on the test psql server
  become: true
  run_once: true
  delegate_to: "{{ postgres_host }}"
  ansible.builtin.apt:
    name:
      - libpq-dev
      - python3-dev
      - python3-psycopg2
      - "postgresql-client-{{ postgres_version }}"
    state: present
    update_cache: true

- name: Ensure postgres user account for app exists
  run_once: true
  delegate_to: "{{ postgres_host }}"
  become: true
  community.postgresql.postgresql_user:
    name: "{{ application_dbuser_name }}"
    login_host: "{{ postgres_host }}"
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ vault_postgres_admin_password }}"
    password: "{{ application_dbuser_password }}"
    encrypted: true
    role_attr_flags: "{{ application_dbuser_role_attr_flags }}"
    state: "present"
