---
- name: Setup Postgres Client and Configuration
  when: postgres_setup_enabled | bool
  block:
    - name: Make sure CA certificates are available
      become: true
      ansible.builtin.apt:
        pkg: ca-certificates
        state: present

    - name: Add postgres repository apt-key
      become: true
      ansible.builtin.apt_key:
        url: "{{ postgres_apt_key_url }}"
        state: present

    - name: Add postgres repository
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ postgres_apt_repository }}"
        update_cache: true
        state: present

    - name: Install postgres client libraries
      become: true
      ansible.builtin.apt:
        name:
          - libpq-dev
          - python3-dev
          - python3-psycopg2
          - "postgresql-client-{{ postgres_version }}"
        state: present
        update_cache: true

    - name: Ensure access to postgres server
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        line: "host    all             all             {{ ansible_default_ipv4.address }}/32       md5"
      delegate_to: "{{ postgres_host }}"
      notify: Reload remote postgres

- name: Create postgres user
  ansible.builtin.import_tasks: create_user.yml
  when: postgres_setup_enabled | bool

- name: Create postgres database
  ansible.builtin.import_tasks: create_db.yml
  when: postgres_setup_enabled | bool

- name: Backup postgres database
  ansible.builtin.import_tasks: backup_db.yml
  when: postgres_backup_enabled | bool
