---
- name: set fqdn for use in pg_hba
  ansible.builtin.set_fact:
    "pg_hba_fqdn={{ ansible_facts['fqdn'] }}"

- name: Ensure access to postgres server
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    line: "host    all             all             {{ pg_hba_fqdn }}       md5"
  delegate_to: "{{ postgres_host }}"
  notify: Reload remote postgres

- name: Ensure postgres user account for app exists
  run_once: true
  delegate_to: "{{ postgres_host }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ application_dbuser_name }}"
    # login_host: "{{ postgres_host }}"
    # login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ vault_postgres_admin_password }}"
    password: "{{ application_dbuser_password }}"
    encrypted: true
    role_attr_flags: "{{ application_dbuser_role_attr_flags }}"
    state: "present"

- name: Ensure postgres database for app exists
  delegate_to: "{{ postgres_host }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ application_db_name }}"
    # login_host: "{{ postgres_host }}"
    # login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ vault_postgres_admin_password }}"
    encoding: "UTF-8"
    owner: "{{ application_dbuser_name }}"
    state: "present"
  # changed_when: false
