---
- name: Verify
  hosts: instance
  gather_facts: false
  tasks:
  - name: test for pulmap directory existence
    stat:
      path: "{{ item }}"
    loop:
      - "/opt/ruby_app/shared/tmp"
    register: pulmap_dir
    failed_when:
      - not pulmap_dir.stat.exists
      - not pulmap_dir.stat.isdir
