---
galaxy_info:
  role_name: psql-client
  author: Princeton University Library
  description: Set up a remote postgres database and user
  license: Apache-2.0

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - postgresql
    - database
    - backup
    - ubuntu
