---
galaxy_info:
  author: cdh
  description: Set up a remote postgres database and user
  company: Center for Digital Humanities @ Princeton
  license: Apache-2.0

  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - postgresql
    - database
    - backup
    - ubuntu

dependencies:
  - role: setup
