---
# defaults file for roles/repec
rails_app_name: "repec"
rails_app_directory: "repec"
rails_app_env: "staging"
app_secret_key: 'key'
app_db_name: 'repec'
app_db_user: 'repec'
app_db_password: 'repec'
app_db_host: 'localhost'
app_host_name: 'localhost'
application_host_protocol: 'http'
repec_secret_key_base: 'default_key'
# postgres test VM settings
postgres_port: 5432
postgres_version: 15
postgres_host: postgres
postgres_admin_user: postgres
vault_postgres_admin_password: postgres
postgres_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
