---
analytics_secret_key_base: '{{vault_analytics_production_secret_key}}'
analytics_db_name: 'analytics_production'
analytics_db_user: 'analytics_production'
analytics_db_password: '{{ vault_analytics_production_db_password }}'
analytics_db_host: 'lib-postgres-prod1.princeton.edu'
analytics_db_admin_user: "postgres"
analytics_nomad_env_vars:
  SECRET_KEY_BASE: '{{ analytics_secret_key_base }}'
  DB_NAME: '{{ analytics_db_name }}'
  DB_USER: '{{ analytics_db_user }}'
  DB_PASSWORD: '{{ analytics_db_password }}'
  POSTGRES_HOST: '{{ analytics_db_host }}'
