---
analytics_secret_key_base: '{{vault_analytics_production_secret_key}}'
db_name: 'analytics_production'
db_user: 'analytics_production'
db_password: '{{ vault_analytics_production_db_password }}'
db_host: 'lib-postgres-prod1.princeton.edu'
db_admin_user: "postgres"
nomad_job: "analytics-production"
database_connections:
  - db_host: '{{ db_host }}'
    db_name: '{{ db_name }}'
    db_user: '{{ db_user }}'
    db_owner: '{{ db_user }}'
    db_password: '{{ db_password }}'
    db_admin_user: "{{ db_admin_user }}"
nomad_vars:
  # Job name
  analytics-production:
    SECRET_KEY_BASE: '{{ analytics_secret_key_base }}'
    DB_NAME: '{{ analytics_db_name }}'
    DB_USER: '{{ analytics_db_user }}'
    DB_PASSWORD: '{{ analytics_db_password }}'
    POSTGRES_HOST: '{{ analytics_db_host }}'
