---
analytics_secret_key_base: '{{vault_analytics_staging_secret_key}}'
db_name: 'analytics_staging'
db_user: 'analytics_staging'
db_password: '{{ vault_analytics_staging_db_password }}'
db_host: 'lib-postgres-staging1.princeton.edu'
db_admin_user: "postgres"
database_connections:
  - db_host: '{{ db_host }}'
    db_name: '{{ db_name }}'
    db_user: '{{ db_user }}'
    db_owner: '{{ db_user }}'
    db_password: '{{ db_password }}'
    db_admin_user: "{{ db_admin_user }}"
nomad_vars:
  # Job name
  analytics-staging:
    SECRET_KEY_BASE: '{{ analytics_secret_key_base }}'
    DB_NAME: '{{ db_name }}'
    DB_USER: '{{ db_user }}'
    DB_PASSWORD: '{{ db_password }}'
    POSTGRES_HOST: '{{ db_host }}'
