#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/k8s_nfs

- name: reload nfs exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: restart nfs server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
