---
reservoir_sandbox_db_version: '15'
reservoir_sandbox_db_host: 'lib-postgres-staging1.princeton.edu'
reservoir_nomad_env_vars:
  DB_USERNAME: '{{ vault_nomad_db_username }}'
  DB_PASSWORD: '{{ vault_nomad_db_password }}'
  DB_DATABASE: '{{ vault_nomad_db_name }}'
  DB_HOST: '{{ vault_nomad_db_host }}'
