# Ansible managed
server {
    listen 80;
    server_name lae-staging.princeton.edu;

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lae-staging.princeton.edu;

    ssl_certificate            /etc/letsencrypt/live/lae-staging/fullchain.pem;
    ssl_certificate_key        /etc/letsencrypt/live/lae-staging/privkey.pem;
    ssl_session_cache          shared:SSL:1m;
    ssl_prefer_server_ciphers  on;

    # /catalog/<id> goes to /item/<id>
    location ~ ^/catalog/(.+)$ {
        return 301 https://dpul-collections-staging.lib.princeton.edu/item/$1;
    }

    # All other paths go to digital collections LAE landing page.
    location / {
        return 301 https://dpul-collections-staging.lib.princeton.edu/collections/lae;
    }
}
