# Ansible managed
#
proxy_cache_path /var/cache/nginx/lib-px-staging/ keys_zone=lib-px-stagingcache:10m;

upstream lib-px-staging {
    least_time header 'inflight';
    zone lib-px-staging 64k;
    server lib-pxser01a.princeton.edu:8006 resolve;
    server lib-pxser02a.princeton.edu:8006 resolve;
    server lib-pxser03a.princeton.edu:8006 resolve;
    sticky learn
          create=$upstream_cookie_lib-px-stagingcookie
          lookup=$cookie_lib-px-stagingcookie
          zone=lib-px-stagingclient_sessions:1m;
}

server {
    listen 8006;
    server_name lib-px-staging.lib.princeton.edu;

    client_max_body_size 0;

    access_log off;
    error_log off;

    ssl_certificate            /etc/letsencrypt/live/lib-px-staging.lib/fullchain.pem;
    ssl_certificate_key        /etc/letsencrypt/live/lib-px-staging.lib/privkey.pem;
    ssl_session_cache          shared:SSL:1m;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass https://lib-px-staging;
        proxy_cache_methods POST;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
        proxy_connect_timeout      450;
        proxy_send_timeout         450;
        proxy_read_timeout         450;
        proxy_cache_revalidate on;
        proxy_cache_min_uses 3;
        proxy_cache_use_stale error timeout updating http_500 http_502
                              http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        health_check uri=/solr;
        # allow libnet network
        allow 128.112.200.0/21;
        # allow ip4-library-servers network
        allow 172.20.80.0/22;
        # block all
        deny all;
    }

}