otel_exporter {
    endpoint 127.0.0.1:4317;
}

otel_service_name nginxplus-lb;

otel_resource_attr deployment.environment staging;
otel_resource_attr host.name $hostname;

otel_trace on;
otel_trace_context propagate;

otel_span_name "$request_method $host$request_uri";

otel_span_attr http.method $request_method;
otel_span_attr http.target $request_uri;
otel_span_attr http.host $host;
otel_span_attr http.status_code $status;
otel_span_attr http.user_agent $http_user_agent;
otel_span_attr net.peer.ip $remote_addr;
otel_span_attr nginx.server_name $server_name;
