# {{ ansible_managed | comment }}

server {
    listen 127.0.0.1:18080;
    server_name localhost;

    access_log off;

    location = /nginx_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}
