upstream sandbox_openpencil_upstream {
    zone sandbox_openpensil_upstream 64k;
    server sandbox-openpencil1.lib.princeton.edu:443;
}

server {
    listen 443 ssl http2;
    server_name sandbox-openpencil.lib.princeton.edu;

    ssl_certificate     /etc/letsencrypt/live/sandbox-openpencil.lib/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sandbox-openpencil.lib/privkey.pem;

    location / {
        proxy_pass https://sandbox_openpencil_upstream;

        proxy_buffer_size 64k;
        proxy_buffers 8 64k;
        proxy_busy_buffers_size 128k;

        proxy_ssl_server_name on;
        proxy_ssl_name sandbox-openpencil1.lib.princeton.edu;

        proxy_set_header Host sandbox-openpencil.lib.princeton.edu;
        proxy_set_header X-Forwarded-Host sandbox-openpencil.lib.princeton.edu;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
