---
- name: OpenDistro | add elastic key
  apt_key:
    url: https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
    state: present

- name: OpenDistro | add OpenDistro repository
  apt_repository:
    repo: "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main"
    state: present
    filename: opendistroforelasticsearch

- name: OpenDistro | install elasticsearch OSS
  apt:
    deb: "https://{{ elastic_url }}/downloads/elasticsearch/elasticsearch-oss-{{ elastic_version }}-amd64.deb"
