desired_nodejs_version: 'v26.8.1'
install_ruby_from_source: true
passenger_ruby: "/usr/local/bin/ruby"
ruby_version_override: "ruby-3.4.1"
passenger_extra_http_config:
  - "passenger_preload_bundler on;"
rails_app_vars:
  - name: LDAP_USERNAME
    value: '{{ vault_lockers_and_study_spaces_ldap_username }}'
  - name: LDAP_PASSWORD
    value: '{{ vault_lockers_and_study_spaces_ldap_password }}'
