---
- name: Converge
  hosts: all
  become: true
  vars:
    running_on_server: false
    install_mailcatcher: true
    mailcatcher_http_port: 1080
    mailcatcher_smtp_port: 1025
  pre_tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
  tasks:
    - name: "Include mailcatcher"
      ansible.builtin.include_role:
        name: mailcatcher
