---
## Create Mounts
- name: bibdata | ensure presence of nfs mount
  ansible.posix.mount:
    src: "{{ nfs_server }}:/var/nfs/bibdata"
    path: "/mnt/nfs/bibdata"
    state: mounted
    fstype: nfs
    opts: rw,sync,hard
  become: true
  when: running_on_server

- name: bibdata | Create data directory
  ansible.builtin.file:
    path: '{{ bibdata_data_dir | dirname }}'
    state: directory
    recurse: true
    owner: '{{ deploy_user }}'
    group: 'www-data'

# New: Create symlink to nfs mount
- name: bibdata | Create symlink to nfs mount
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.link }}'
    owner: '{{ deploy_user }}'
    group: 'www-data'
    state: 'link'
    force: true
  when: running_on_server
  with_items:
    - src: '/mnt/nfs/bibdata'
      link: '{{ bibdata_data_dir }}'

- name: bibdata | Create mount directory structure
  ansible.builtin.file:
    path: '/{{ item }}'
    state: 'directory'
    owner: '{{ deploy_user }}'
    group: 'www-data'
    mode: 0755
  when: running_on_server
  with_items:
    - '{{ bibdata_data_dir }}/scsb_update_files'
    - '{{ bibdata_data_dir }}/figgy_ark_cache'
