---
## Create Mounts
- name: bibdata | ensure presence of nfs mount
  ansible.posix.mount:
    src: "{{ nfs_server }}:/var/nfs/bibdata"
    path: "/mnt/nfs/bibdata"
    state: mounted
    fstype: nfs
    opts: rw,sync,hard
  become: true
  when: running_on_server

# New: Create symlink to nfs mount
- name: Create a symbolic link
  ansible.builtin.file:
    src: '/mnt/nfs/bibdata'
    dest: '/data/bibdata_files'
    # owner: '{{ deploy_user }}'
    # group: '{{ deploy_user }}'
    state: link

# - name: bibdata | Create symlink to nfs mount
#   ansible.builtin.file:
#     src: '{{ item.src }}'
#     dest: '{{ item.link }}'
#     owner: '{{ deploy_user }}'
#     group: 'www-data'
#     state: 'link'
#     force: true
#   when: running_on_server
#   with_items:
#     - src: '/mnt/nfs/bibdata'
#       link: '/data/bibdata_files'

# - name: bibdata | Create data directory
#   ansible.builtin.file:
#     path: '/data/bibdata_files'
#     state: directory
#     recurse: true

- name: bibdata | Create mount directory structure
  ansible.builtin.file:
    path: '/{{ item }}'
    state: 'directory'
    owner: '{{ deploy_user }}'
    group: 'www-data'
    mode: 0755
  when: running_on_server
  with_items:
    - '/data/bibdata_files/scsb_update_files'
    - '/data/bibdata_files/figgy_ark_cache'


