---
- name: restart chrony
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    state: restarted
  when:
    - running_on_server | default(true)

- name: test logrotate configuration
  ansible.builtin.command: "logrotate -f {{ common_logrotate_conf }}"
  register: logrotate_test
  failed_when: logrotate_test.rc != 0
  when:
    - running_on_server | default(true)

- name: reload logrotate timer settings
  ansible.builtin.systemd:
    daemon_reload: true
    name: logrotate.timer
    enabled: true
  when:
    - running_on_server | default(true)
    - ansible_service_mgr == "systemd"

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when:
    - ansible_service_mgr == "systemd"
