---
- name: Nomad App | configure postgres
  ansible.builtin.include_tasks: database_setup.yml
  loop: "{{ database_connections }}"
  no_log: true
  when:
    - running_on_server
- name: 'Nomad App | set nomad variables'
  when:
    - nomad_vars is defined
    - running_on_server
  loop: "{{ nomad_vars | dict2items }}"
  no_log: true
  ansible.builtin.shell:
    cmd: >
      /usr/local/bin/nomad var put -force 
      nomad/jobs/{{ item.key }}
      {{ item.value.keys() | zip(item.value.values()) | map("join", "=") | join(" ") }}
  environment:
    NOMAD_TOKEN: '{{ pul_nomad_management_token }}'
    run_once: true
