#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/openresty

- name: restart altcha server
  ansible.builtin.service:
    name: altcha_server
    state: restarted

- name: reload openresty
  ansible.builtin.service:
    name: openresty
    state: reloaded
