---
abid_production_secret_key_base: '{{vault_abid_production_secret_key}}'
db_name: 'abid_prod'
db_user: 'abid_production'
db_password: '{{ vault_abid_production_db_password }}'
db_host: 'lib-postgres-prod1.princeton.edu'
db_admin_user: "postgres"
database_connections:
  - db_host: '{{ db_host }}'
    db_name: '{{ db_name }}'
    db_user: '{{ db_user }}'
    db_owner: '{{ db_user }}'
    db_password: '{{ db_password }}'
    db_admin_user: "{{ db_admin_user }}"
nomad_vars:
  abid-production:
    ABID_SECRET_KEY_BASE: '{{ abid_production_secret_key_base }}'
    APP_DB: '{{ db_name }}'
    APP_DB_USERNAME: '{{ db_user }}'
    APP_DB_PASSWORD: '{{ db_password }}'
    APP_DB_HOST: '{{ db_host }}'
    HONEYBADGER_API_KEY: '{{ vault_abid_honeybadger_key }}'
    ASPACE_USER: '{{ vault_abid_aspace_production_user }}'
    ASPACE_PASSWORD: '{{ vault_abid_aspace_production_password }}'
    ALMA_API_KEY: '{{ vault_abid_alma_prod_key }}'
    RAILS_MASTER_KEY: '{{ vault_rails_master_key }}'
