---
abid_staging_secret_key_base: '{{vault_abid_staging_secret_key}}'
db_name: 'abid_staging'
db_user: 'abid_staging'
db_password: '{{ vault_abid_staging_db_password }}'
db_host: 'lib-postgres-staging1.princeton.edu'
db_admin_user: "postgres"
nomad_vars:
  abid-staging:
    ABID_SECRET_KEY_BASE: '{{ abid_staging_secret_key_base }}'
    APP_DB: '{{ db_name }}'
    APP_DB_USERNAME: '{{ db_user }}'
    APP_DB_PASSWORD: '{{ db_password }}'
    APP_DB_HOST: '{{ db_host }}'
    HONEYBADGER_API_KEY: '{{ vault_abid_honeybadger_key }}'
    ASPACE_USER: '{{ vault_abid_aspace_staging_user }}'
    ASPACE_PASSWORD: '{{ vault_abid_aspace_staging_password }}'
    ALMA_API_KEY: '{{ vault_abid_alma_sandbox_key }}'
    RAILS_MASTER_KEY: '{{ vault_rails_master_key }}'
