---
rails_app_env: "production"
# postgres test VM settings
postgres_port: 5432
postgres_version: 15
postgres_host: postgres
postgres_admin_user: postgres
vault_postgres_admin_password: postgres
postgres_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
