---
- name: Converge
  hosts: all
  vars:
    running_on_server: false
    nodejs_yarn_berry_enabled: true
    desired_nodejs_version: v18.18.2
  become: true
  pre_tasks:
    - name: Install GPG requirement for testing
      ansible.builtin.apt:
        name: gnupg
        state: present
  tasks:
    - name: "Include nodejs"
      ansible.builtin.include_role:
        name: nodejs
