---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    nodejs_yarn_berry_enabled: true
    desired_nodejs_version: v18.18.2
    nodejs_yarn_berry_version: "4.15.0"
  tasks:
    - name: Verify node is installed
      ansible.builtin.command:
        cmd: /usr/local/bin/node --version
      register: nodejs_verify_node
      changed_when: false

    - name: Verify corepack is installed
      ansible.builtin.command:
        cmd: /usr/local/bin/corepack --version
      register: nodejs_verify_corepack
      changed_when: false

    - name: Verify Yarn Berry version
      ansible.builtin.command:
        cmd: /usr/local/bin/yarn --version
      environment:
        COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      register: nodejs_verify_yarn
      changed_when: false

    - name: Assert expected Node and Yarn versions
      ansible.builtin.assert:
        that:
          - nodejs_verify_node.stdout == desired_nodejs_version
          - nodejs_verify_yarn.stdout == nodejs_yarn_berry_version
