---
# you MUST run this playbook on a single host with '--limit'
# example:
# ansible-playbook -v -e domain_name=datacommons --limit adc-prod2.princeton.edu playbooks/utils/incommon_certbot.yml
#
# This playbook will need to be run on both load balancers sequentially.
# The domain_name will also be the certbot cert-name and live directory:
# /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
#
# If a valid certificate already exists, the existing certificate may need to be revoked
# or deleted before this playbook will change the system.

- name: add incommon certinext acme for {{ domain_name }}
  hosts: nginxplus_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true

  vars_files:
    - ../../group_vars/all/vault.yml
    - ../../group_vars/all/vars.yml

  pre_tasks:
    - name: stop playbook if you didn't use --limit
      ansible.builtin.fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

  tasks:
    - name: install certbot software
      ansible.builtin.apt:
        name: certbot
        state: present

    - name: update acme certificates for {{ domain_name }}
      ansible.builtin.command:
        argv:
          - /usr/bin/certbot
          - certonly
          - --standalone
          - --non-interactive
          - --agree-tos
          - --email
          - lsupport@princeton.edu
          - --server
          - https://acme-us.certinext.io/v1/directory
          - --eab-kid
          - "{{ vault_certinext_acme_eab_kid }}"
          - --eab-hmac-key
          - "{{ vault_certinext_acme_eab_hmac_key }}"
          - --domain
          - "{{ domain_name }}.princeton.edu"
          - --cert-name
          - "{{ domain_name }}"
      register: certbot_result
      changed_when: "'Successfully received certificate' in certbot_result.stdout"

    - name: tell everyone on slack you ran an ansible playbook
      community.general.slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}"
        channel: "{{ item }}"
      loop: "{{ [slack_alerts_channel] if slack_alerts_channel is string else slack_alerts_channel }}"
      tags: always
      become: false
