---
# To run the playbook:
# ansible-playbook playbooks/utils/checkmk_agent.yml --limit=<machine/group> -e checkmk_folder=linux/rdss
# folder names must be all lower case and should not begin with a slash
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: Install CheckMk agent on host
  hosts: "{{ runtime_env | default ('staging') }}"
  remote_user: pulsys
  become: true

  vars_files:
    - ../../group_vars/all/vault.yml
    - ../../group_vars/checkmk/{{ runtime_env | default('staging') }}.yml
    - ../../group_vars/checkmk/vault.yml

  vars:
  pre_tasks:
    - name: Debug checkmk_agent_host_name
      ansible.builtin.debug:
        msg: "checkmk_agent_host_name: {{ checkmk_agent_host_name }}"

    - name: Debug checkmk_agent_folder
      ansible.builtin.debug:
        msg: "checkmk_agent_folder: {{ checkmk_agent_folder }}"

    - name: Debug checkmk_agent_user
      ansible.builtin.debug:
        msg: "checkmk_agent_user: {{ checkmk_agent_user }}"

    - name: Debug checkmk_agent_pass
      ansible.builtin.debug:
        msg: "checkmk_agent_auth: {{ checkmk_agent_pass }}"

  tasks:
    - name: Install and configure Checkmk agent
      ansible.builtin.import_role:
        name: checkmk.general.agent
