---
# This playbook checks whether Tower can connect to all hosts in inventory
# this should enable us to identify and solve connection problems
#
- name: confirm Ansible access to all inventory
  hosts: all
  remote_user: pulsys
  become: true
  vars_files:
    - ../../group_vars/all/vars.yml
    - ../../group_vars/all/vault.yml

  tasks:
  # connection failures should happen in the Gather Facts section
  - name: Report success of connection
    ansible.builtin.debug:
      msg: Ansible successfully connected to {{ inventory_hostname }}
