---
- name: get issues from GitLab
  hosts: localhost
  tasks:
    - name: call issue API
      ansible.builtin.uri:
        url: "https://gitlab.lib.princeton.edu/api/v4/issues?scope=all&project_id=5"
        method: GET
        # 'scope=all' pulls issues created by all users
      register: api_output

    - name: view results
      ansible.builtin.debug:
        var: api_output

#    - name: select our data
 #     ansible.what???:
        #what we want is:
          # api_output.json.[#]. and then title, iid (that's not a typo), state, assignee.name, created_at, labels, and web_url
