---
# This playbook checks for OIT mandated security tools Rapid7 and Cortex XDR
# across the infrastructure we automate with Ansible
# if there's a service called "traps_pmd", then Cortex XDR is installed
# if there's a service called "ir_agent", then Rapid7 is installed
#
- name: audit OIT Security Tools
  hosts: all
  remote_user: pulsys
  become: true
  # serial: "{{ concurrent_vms | default('5') }}"
  vars_files:
    - ../../group_vars/all/vars.yml
    - ../../group_vars/all/vault.yml

  pre_tasks:
  - name: Populate service facts
    ansible.builtin.service_facts:

  tasks:
  - name: Report presence of XDR service (traps_pmd)
    ansible.builtin.debug:
      msg: The traps_pmd service exists on {{ inventory_hostname }}
    when:
      - "'traps_pmd.service' in ansible_facts.services"

  - name: Report presence of Rapid7 service (ir_agent)
    ansible.builtin.debug:
      msg: The ir_agent service exists on {{ inventory_hostname }}
    when:
      - "'ir_agent.service' in ansible_facts.services"
