---
#  This playbook will install OIT recommended security tools Rapid7 and Crowdstrike
# By default this playbook runs on all hosts in the three environment groups. To run against a single host or group, use '--limit <group_or_host_name>'. For example '--limit qa' or '--limit figgy-web-staging1.princeton.edu'."
#
- name: install OIT Security Tools on a host
  hosts: staging:qa:production
  remote_user: pulsys
  serial: "{{ concurrent_vms | default('5') }}"
  # roles already add 'become' so don't to it here
  # for the falcon install portion
  # become: true
  # 
  # Ansible Platform 2.5 has been released - wait to upgrade except 
  # go ahead and use EDA version 2.5, which works with our existing 2.4
  # this gives us enterprise functionality - SSO, horizontal scaling (multiple
  # rulebook sources) this is known as "event streams"
  # GA of 2.5 by Nov. 1
  #
  vars_files:
    - ../../group_vars/crowdstrike/vault.yml
    - ../../group_vars/crowdstrike/vars.yml
    - ../../group_vars/all/vars.yml
    - ../../group_vars/all/vault.yml

  pre-tasks:
  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Populate package facts
    ansible.builtin.package_facts:

  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_client_id: <FALCON_CLIENT_ID>
      falcon_client_secret: <FALCON_CLIENT_SECRET>
      falcon_sensor_version_decrement: 2
      # be sure to add this so we don't download if we don't need to
      falcon_api_sensor_download_path: /opt/install/

  - role: crowdstrike.falcon.falcon_configure
    vars:
      falcon_client_id: <FALCON_CLIENT_ID>
      falcon_client_secret: <FALCON_CLIENT_SECRET>

  tasks:
  # - name: Create bigfix directory
  #   ansible.builtin.file:
  #     path: /etc/opt/BESClient
  #     state: directory
  #     mode: '0755'
  #   when:
  #     - "ansible_facts.services['besclient.service'] is not defined"

  # - name: Download BigFix masthead
  #   ansible.builtin.get_url:
  #     url: "{{ vault_bigfix_url }}"
  #     dest: "/etc/opt/BESClient/actionsite.afxm"
  #     owner: root
  #     group: root
  #     mode: "0600"
  #   when: "ansible_facts.services['besclient.service'] is not defined"

  # - name: Download the bigfix deb file
  #   ansible.builtin.get_url:
  #     url: "https://software.bigfix.com/download/bes/100/BESAgent-10.0.7.52-debian6.amd64.deb"
  #     dest: "/tmp/BESAgent-10.0.7.52-debian6.amd64.deb"
  #     owner: pulsys
  #     group: pulsys
  #     mode: "0644"
  #   when: "ansible_facts.services['besclient.service'] is not defined"

  # WIP: use the crowdstrike collection

  # we might want to gather auth using
  # https://crowdstrike.github.io/ansible_collection_falcon/auth_module.html#ansible-collections-crowdstrike-falcon-auth-module

  # all modules in the crowdstrike.falcon collection
  # require the pip package crowdstrike-falconpy
  # we can install it on Tower, I think, download the files to there, and then
  # use the copy module
  # or we can split this out, downloading the files to our filesystem in one play and
  # installing them in another one . . .

  - name: get the hash for RHEL sensor file
    crowdstrike.falcon.sensor_download_info:
      client_id: "{{ vault_crowdstrike_client_id }}"
      client_secret: "{{ vault_crowdstrike_secret }}"
      filter: "platform:'linux' + os:'RHEL' + os_version:'9 - arm64' "
      sort: "version|desc"
    delegate_to: localhost
    become: false
    register: RHEL_falcon_versions

  - name: sort list of RHEL falcon versions by date
    ansible.builtin.set_fact:
      RHEL_date_ordered:  "{{ RHEL_falcon_versions.installers | sort(attribute='release_date') | reverse }}"

  - name: view date-sorted list
    ansible.builtin.debug:
      var: RHEL_date_ordered

  - name: Download the Falcon sensor file for RHEL
    crowdstrike.falcon.sensor_download:
      client_id: "{{ vault_crowdstrike_client_id }}"
      client_secret: "{{ vault_crowdstrike_secret }}"
      # skips the current latest release and the previous release, using N-2
      hash: "{{ RHEL_date_ordered[2].sha256 }}"
      dest: "/tmp/"
      owner: pulsys
      group: pulsys
      mode: "0644"
    when:
      - "'falcon-sensor' not in ansible_facts.packages"
      - ansible_os_family == "RedHat"

  - name: get the hash for Ubuntu sensor file
    crowdstrike.falcon.sensor_download_info:
      client_id: "{{ vault_crowdstrike_client_id }}"
      client_secret: "{{ vault_crowdstrike_secret }}"
      filter: "platform:'linux' + os:'Ubuntu'"
      sort: "version|desc"
    delegate_to: localhost
    become: false
    register: Ubuntu_falcon_versions

  - name: sort list of Ubuntu falcon versions by date
    ansible.builtin.set_fact:
      Ubuntu_date_ordered:  "{{ Ubuntu_falcon_versions.installers | sort(attribute='release_date') | reverse }}"

  - name: view date-sorted list
    ansible.builtin.debug:
      var: Ubuntu_date_ordered

  # when set up this way, works on my laptop
  # we probably want this to run at the top with
  # run_once: true
  - name: Download the Falcon sensor file for Ubuntu
    crowdstrike.falcon.sensor_download:
      client_id: "{{ vault_crowdstrike_client_id }}"
      client_secret: "{{ vault_crowdstrike_secret }}"
      # skips the current latest release and the previous release, using N-2
      hash: "{{ Ubuntu_date_ordered[2].sha256 }}"
      dest: "/Users/alicia/"
      owner: alicia
      group: staff
      mode: "0644"
    become: false
    delegate_to: localhost
    when:
      - "'falcon-sensor' not in ansible_facts.packages"
      - ansible_os_family == "Debian"

  # https://crowdstrike.github.io/ansible_collection_falcon/sensor_download_info_module.html
  # - name: Download the Falcon sensor deb file
  #   crowdstrike.falcon.sensor_download:
  #     # https://crowdstrike.github.io/ansible_collection_falcon/sensor_download_module.html#ansible-collections-crowdstrike-falcon-sensor-download-module
  #     client_id: "{{ vault_crowdstrike_client_id }}"
  #     client_secret: "{{ vault_crowdstrike_secret }}"
  #     hash: "{{ falcon_versions.??? }}"
  #     dest: "/tmp/"
  #     owner: pulsys
  #     group: pulsys
  #     mode: "0644"
  #   when:
  #     - "'falcon-sensor' not in ansible_facts.packages"
  #     - ansible_os_family == "RedHat"


  # - name: install BESClient agent
  #   ansible.builtin.apt:
  #     deb: "/tmp/BESAgent-10.0.7.52-debian6.amd64.deb"
  #   when: "ansible_facts.services['besclient.service'] is not defined"

  # - name: Launch the BigFix client
  #   ansible.builtin.command: /etc/init.d/besclient start
  #   when: "ansible_facts.services['besclient.service'] is not defined"

# do not need to do the install/launch/start/enable tasks - the roles will take care of it
  - name: install crowdstrike falcon sensor agent
    ansible.builtin.apt:
      deb: "/tmp/{{ some_registered_var }}"
    when:
      - "'falcon-sensor' not in ansible_facts.packages"

  - name: launch crowdstrike falcon agent
  # pass the CID into the falcon configure role
    command: /opt/CrowdStrike/falconctl -s --cid={{ princeton_cid }}
    become: true
    when:
      - "'falcon-sensor' not in ansible_facts.packages"

  - name: start and enable crowdstrike falcon agent
    ansible.builtin.systemd_service:
      name: "falcon-sensor"
      enabled: true
      state: started
    when:
      - "'falcon-sensor' not in ansible_facts.packages"

  - name: Check for rapid7 path
    ansible.builtin.stat:
      path: /opt/rapid7
    register: rapid7_home

  - name: create new rapid7 directory
    ansible.builtin.file:
      path: /opt/rapid7
      state: directory
    when:
      - not rapid7_home.stat.exists

  - name: Copy Rapid7 install script to box
    ansible.builtin.copy:
      src: ../../bin/Rapid7_agent_installer.sh
      dest: /opt/rapid7/
      owner: pulsys
      group: pulsys
      mode: '0744'
    become: true
    when:
      - not rapid7_home.stat.exists

  - name: Execute Rapid7 install script
    ansible.builtin.shell: sudo /opt/rapid7/Rapid7_agent_installer.sh install_start --token {{ vault_Rapid7_token }} --attributes="Library Systems"
    when:
      - not rapid7_home.stat.exists

  - name: Restart or start rapid7
    ansible.builtin.service:
      name: ir_agent
      state: started
    when:
      - not rapid7_home.stat.exists

  # post_tasks:
  #   - name: send information to slack
  #     ansible.builtin.include_tasks:
  #       file: slack_tasks_end_of_playbook.yml
