---
# You MUST run this playbook with --limit.
#
- name: Configure host firewall
  hosts: all
  # hosts: staging:qa:production
  remote_user: pulsys
  become: true
  vars:
    running_on_server: true
  vars_files:
    - ../../group_vars/all/vars.yml

  pre_tasks:
    - name: stop playbook if you didn't pass --limit
      fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    - name: display IP addresses
      ansible.builtin.debug:
        var: ansible_default_ipv4.address

  roles:
    - role: roles/firewall
      when: ansible_default_ipv4.address is match("172.20.80")
      # do not install UFW on VMs with public-facing libnet IPs
