---
- name: Get info on VEEAM backup tags from vSphere
  hosts: localhost

  vars_files:
    - ../../group_vars/vsphere/vault.yml
    - ../../group_vars/vsphere/{{ runtime_env | default('staging') }}.yml

  vars:
    - vm_tags_dict: "{{ tagged_vms.virtual_machines.tags }}"
    # - fake_wed_vms: "{{ tagged_vms.virtual_machines | selectattr('tags[0].name', 'equalto', 'Fake_Wed_A') }}"
    - fake_tue_vms: "{{ tagged_vms.virtual_machines | selectattr('tags[0].name', 'equalto', 'Fake_Tue_A') }}"
    - known_tagged_vm: "{{ tagged_vms.virtual_machines | selectattr('guest_name', 'equalto', 'dss-staging1') }}"
    - fake_wed_vms: "{{ tagged_vms.virtual_machines | selectattr('tags') | flatten | selectattr('name', 'equalto', 'Fake_Wed_A') }}"
    # the formulation below works, but returns only the 'tags' dicts
    # we need to see the name of the VM and eventually the disk space
    # - fake_wed_vms: "{{ tagged_vms.virtual_machines | map(attribute='tags') | flatten | selectattr('name', 'equalto', 'Fake_Wed_A') }}"

  tasks:
    - name: Gather info on tags and storage
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        show_tag: true
        show_allocated: true
      register: tagged_vms

    - name: View full variable
      ansible.builtin.debug:
        var: tagged_vms

    - name: view selectattr vars - one VM
      ansible.builtin.debug:
        var: known_tagged_vm

    - name: view all tags with mapped vars
      ansible.builtin.debug:
        msg: "{{ tagged_vms.virtual_machines | map(attribute='tags') | flatten | map(attribute='name') }}"

    - name: view selectattr vars - Wed
      ansible.builtin.debug:
        msg: These are the Weds VMs {{ tagged_vms.virtual_machines | map(attribute='tags') | first | selectattr('name', 'equalto', 'Fake_Wed_A') }}
        # using the fake_wed_vms var gives us "success" and the message "VARIABLE IS NOT DEFINED"

    # - name: View vms with tags
    #   ansible.builtin.debug:
    #     msg: The {{ tagged_vms.virtual_machines | map(attribute='guest_name') }} vm has {{ tagged_vms.virtual_machines | map(attribute='tags') }} for tags and {{ tagged_vms.virtual_machines | map(attribute='allocated.storage') }} allocated storage
    #   loop: "{{ tagged_vms.virtual_machines }}"
    #   when: "tagged_vms.virtual_machines.guest_name == 'dss-staging1'"
    # Nope, 'run_once' did not avoid the 'skipping' entries for all the other VMs
    # trying this without the loop
    # without the loop, we can't use 'item.whatnot'

    # - name: sample debug with json query
    #   ansible.builtin.debug:
    #     msg: "{{ item.tags }}"
    #   with_items:
    #     - "{{ tagged_vms.virtual_machines | community.general.json_query(query) }}"
    #   vars:
    #     query: "[?guest_name=='DC0_H0_VM0']"
