---
- name: Get info on VEEAM backup tags from vSphere
  hosts: localhost

  vars_files:
    - ../../group_vars/vsphere/vault.yml
    - ../../group_vars/vsphere/{{ runtime_env | default('staging') }}.yml

  vars:
    backup_tags:
      - Fake_Wed_A
      - Fake_Tue_A

  tasks:
    - name: Gather info on tags and storage
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        show_tag: true
        show_allocated: true
        vm_type: vm
      register: vms_and_tags

    - name: View full variable
      ansible.builtin.debug:
        var: vms_and_tags

    - name: view all tags with mapped vars
      ansible.builtin.debug:
        msg: "{{ vms_and_tags.virtual_machines | map(attribute='tags') | flatten | map(attribute='name') }}"

    - name: Display VMs that have tags
      ansible.builtin.debug:
        var: item
      loop: "{{ vms_and_tags | community.general.json_query(not_null) }}"
      vars:
        not_null: "virtual_machines[?not_null(tags)]"
      # this returns the correct list of 4 VMs - huzzah!
      register: tagged_vms

    - name: what do tagged_vms look like?
      ansible.builtin.debug:
        var: tagged_vms

    # the registered var from this task contained two items in 'results', each one contained:
      # 'item: <name_of_tag>' and
      # 'msg: true'
    # - name: Display VMs with a specific tag
    #   ansible.builtin.debug:
    #     msg: "{{ vms_and_tags | community.general.json_query(match_specific) }}"
    #   vars:
    #     match_specific: "virtual_machines.tags[*].name == {{ item }}"
    #   loop: "{{ backup_tags }}"
    #   register: single_tagged_vms

    # - name: what do single tagged_vms look like?
    #   ansible.builtin.debug:
    #     var: single_tagged_vms

    - name: create a dict of fields we want
      ansible.builtin.set_fact:
        # build a list of VMs with one specific tags
        slim_tagged_vms: "{{ tagged_vms.results[*].item.{VM_name: guest_name, Tag_name: tags[0].name, Disk_size: allocated.storage} }}"

    - name: look at slim_tagged_vms
      ansible.builtin.debug:
        var: slim_tagged_vms
