---
# defaults file for roles/pulibrary.dispatch
slack_app_name: "{{ omit }}"
slack_app_bot_token: "{{ omit }}"
slack_app_secret: "{{ omit }}"
dispatch_home: "/opt/dispatch_docker"
dispatch_email: "{{ omit }}"
dispatch_slack_channel: "{{ omit }}"
dispatch_url_home: "{{ omit }}"
dispatch_user: "dispatch_db_user"
dispatch_password: "{{ omit }}"
