---
# postgres VM settings
postgres_port: 5432
postgres_version: 15
postgres_host: postgres
postgres_admin_user: postgres
vault_postgres_admin_password: postgres
# application settings
application_db_name: app
application_dbuser_name: app_user
application_dbuser_password: changethis
application_dbuser_role_attr_flags: ""
# apt settings
postgres_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_apt_key_path: "/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc"
postgres_apt_repository_uri: "https://apt.postgresql.org/pub/repos/apt"
postgres_apt_source_types: "deb"
postgres_apt_components: "main"
# database creation settings
postgres_database_encoding: "UTF8"
postgres_database_locale: "{{ postgres_locale }}"
postgres_database_lc_collate: "{{ postgres_database_locale }}"
postgres_database_lc_ctype: "{{ postgres_database_locale }}"
postgres_database_template: "template0"

# architecture support
postgres_supported_architecture: "x86_64"
postgres_apt_architecture: "amd64"
postgres_rpm_architecture: "x86_64"

# client package install flags
postgres_client_install_enabled: true
postgres_manage_pgdg_repo: true

postgres_debian_client_packages:
  - "postgresql-client-{{ postgres_version }}"
  - libpq-dev
  - python3-psycopg2

# task settings
deploy_user: deploy
deploy_user_venv: "/home/{{ deploy_user }}/venv"
db_backup_path: "/home/{{ deploy_user }}/last_{{ application_db_name }}.sql"
# feature flags
postgres_setup_enabled: true
postgres_backup_enabled: true

postgres_apt_legacy_source_files:
  - /etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list
  - /etc/apt/sources.list.d/pgdg.list
  - /etc/apt/sources.list.d/postgresql.list
