---
ruby_version_override: "ruby-3.4.8"
postgres_host: "lib-postgres-prod1.princeton.edu"
postgres_version: 15
postgres_admin_user: "postgres"
rails_app_site_config_services:
  - nginx
  - "{{ sneakers_worker_name }}"
pg_hba_contype: "host"
pg_hba_postgresql_user: "all"
pg_hba_postgresql_database: "all"
pg_hba_method: "md5"
pg_hba_source: "{{ ansible_host }}/32"
passenger_server_name: "lae.princeton.edu"
passenger_app_root: "/opt/lae-blacklight/current/public"
passenger_app_env: "production"
passenger_ruby: "/usr/local/bin/ruby"
passenger_extra_http_config:
  - "passenger_preload_bundler on;"
desired_nodejs_version: "v22.10.0"
postgresql_is_local: false
rails_app_name: "lae-blacklight"
rails_app_directory: "lae-blacklight"
rails_app_symlinks: []
rails_app_dependencies:
  - libpq-dev
  - cifs-utils
  - nfs-common
  - libopenjp2-7-dev
  - libmagickwand-dev
  - pkg-config
  - libtool
  - autoconf
lae_db_name: 'lae_production'
lae_db_user: 'lae'
lae_db_password: '{{ vault_lae_db_password }}'
lae_rabbit_user: '{{ vault_rabbit_production_user }}'
lae_rabbit_password: '{{ vault_rabbit_production_password }}'
lae_rabbit_host: '{{ figgy_rabbit_host }}'
lae_rabbit_server: 'amqp://{{ lae_rabbit_user }}:{{ lae_rabbit_password }}@{{ lae_rabbit_host }}:5672'
rails_app_env: "production"
lae_host_name: 'lae.princeton.edu'
lae_honeybadger_key: '{{ vault_lae_honeybadger_key }}'
application_db_name: '{{ lae_db_name }}'
application_dbuser_name: '{{ lae_db_user }}'
application_dbuser_password: '{{ lae_db_password }}'
application_dbuser_role_attr_flags: 'CREATEDB'
application_host: '{{ passenger_server_name }}'
application_host_protocol: 'https'
project_db_host: '{{ postgres_host }}'
rails_app_vars:
  - name: SECRET_KEY_BASE
    value: '{{ vault_lae_secret_key }}'
  - name: LAE_DB
    value: '{{ lae_db_name }}'
  - name: LAE_DB_USERNAME
    value: '{{ lae_db_user }}'
  - name: LAE_DB_PASSWORD
    value: '{{ lae_db_password }}'
  - name: LAE_DB_HOST
    value: '{{ postgres_host }}'
  - name: LAE_RABBIT_SERVER
    value: '{{ lae_rabbit_server }}'
  - name: LAE_RABBITMQ_URL
    value: '{{ lae_rabbit_server }}'
  - name: LAE_RABBITMQ_EXCHANGE
    value: 'figgy_events'
  - name: APPLICATION_HOST
    value: '{{ lae_host_name }}'
  - name: APPLICATION_HOST_PROTOCOL
    value: '{{ application_host_protocol }}'
  - name: SOLR_URL
    value: 'http://lib-solr9-prod.princeton.edu:8983/solr/lae-prod'
  - name: HONEYBADGER_API_KEY
    value: '{{ lae_honeybadger_key }}'
  - name: NODE_OPTIONS
    value: '--openssl-legacy-provider'
sneakers_workers: PlumEventHandler
sneakers_worker_name: lae-sneakers

datadog_api_key: "{{ vault_datadog_key }}"
datadog_config:
  tags: "application:lae, environment:production, type:webserver"
  log_enabled: true
  apm_enabled: true
  process_config:
    enabled: true
  apm_config:
    analyzed_spans:
      lae|rack.request: 1
    filter_tags:
      reject: ["http.useragent:nginx/1.23.4 (health check)", "operation:heartbeat", "operation:job_fetch", "operation:scheduled_push", "operation:scheduled_poller_wait"]
datadog_checks:
  nginx:
    init_config:
    logs:
      - type: file
        path: /var/log/nginx/access.log
        service: lae
        source: nginx
        sourcecategory: http_web_access
        tags: "lae, environment:production, role:lae"
      - type: file
        path: /var/log/nginx/error.log
        service: lae
        source: nginx
        sourcecategory: http_web_access
        tags: "lae, environment:production, role:lae"
  lae_datadog_ruby_check:
    init_config:
    logs:
      - type: file
        path: /opt/lae-blacklight/current/log/production.log
        service: lae
        source: ruby
        sourcecategory: sourcecode
        tags: "lae, environment:production, role:lae"
  http_check:
    init_config:
    instances:
      - name: Solr Health
        url: 'http://localhost/health.json?providers[]=solrstatus'
        include_content: true
        tags:
          - 'http_service:lae'
          - 'http_service_type:health'
          - 'http_service_check:solr'
      - name: Database Health
        url: 'http://localhost/health.json?providers[]=database'
        include_content: true
        tags:
          - 'http_service:lae'
          - 'http_service_type:health'
          - 'http_service_check:postgres'
      - name: SMTP Health
        url: 'http://localhost/health.json?providers[]=smtpstatus'
        include_content: true
        tags:
          - 'http_service:lae'
          - 'http_service_type:health'
          - 'http_service_check:smtp'
# beyla
beyla_enabled: true
beyla_service_name: lae
beyla_environment: production
beyla_otlp_endpoint: "http://127.0.0.1:4318"
beyla_otlp_protocol: "http/protobuf"
beyla_bpf_context_propagation: "all"

beyla_open_ports:
  - 80
# signoz
otel_default_resource_attributes:
  host.name: "{{ inventory_hostname }}"
  service.name: lae
  service.version: production
  environment: production

otel_receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  filelog/nginx-access:
    include: ["/var/log/nginx/access.log*"]
    start_at: end
    operators:
      - type: regex_parser
        regex: '^(?P<remote_addr>[^\s]+) \((?P<remote_user>[^)]*)\) - - \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
        parse_from: body
      - type: time_parser
        parse_from: attributes.time_local
        layout_type: strptime
        layout: '%d/%b/%Y:%H:%M:%S %z'
      - type: add
        field: attributes.log_type
        value: "lae_access"
      - type: add
        field: attributes.service_name
        value: lae_access

  filelog/nginx-error:
    include: ["/var/log/nginx/error.log*"]
    start_at: end
    operators:
      - type: add
        field: attributes.log_type
        value: "lae_error"
      - type: add
        field: attributes.service_name
        value: "lae"

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk: {}
      filesystem: {}
      load: {}
      memory: {}
      network: {}

otel_processors:
  batch:
    send_batch_max_size: 1024
    send_batch_size: 512
    timeout: 30s

otel_exporters:
  loadbalancing:
    routing_key: service
    protocol:
      otlp:
        timeout: 10s
        tls:
          insecure: true
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    resolver:
      static:
        hostnames:
          - k8s-prod1.lib.princeton.edu:32317
          - k8s-prod2.lib.princeton.edu:32317
          - k8s-prod3.lib.princeton.edu:32317

  debug:
    verbosity: basic

otel_service_pipelines:
  logs:
    receivers:
      - filelog/nginx-access
      - filelog/nginx-error
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  metrics:
    receivers:
      - otlp
      - hostmetrics
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  traces:
    receivers:
      - otlp
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
