---
# Pulled from https://dev.to/lovestaco/install-docker-with-ansible-on-ubuntu-official-repo-docker-compose-578b and adjusted according to https://docs.docker.com/engine/install/ubuntu/
- name: 'pul_nomad | nomad | docker | remove conflicting packages'
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: 'pul_nomad | nomad | docker | ensure dependencies are installed'
  ansible.builtin.apt:
    name:
      - bc
      - curl
      - expect
      - git
      - ca-certificates
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: 'pul_nomad | nomad | docker | get dpkg architecture'
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false
  check_mode: false

- name: 'pul_nomad | nomad | docker | create apt keyring directory'
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "pul_nomad | nomad | docker | download Docker's official GPG key"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"
    force: false

- name: 'pul_nomad | nomad | docker | add Docker repository to apt sources'
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: 'pul_nomad | nomad | docker | install Docker Engine and Compose plugin'
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# Setup userns-remap so that jobs don't run with real root ever unless we
# explicitly allow it.
- name: 'pul_nomad | nomad | docker | create dockremap user'
  ansible.builtin.user:
    name: dockremap
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: 'pul_nomad | nomad | docker | add dockremap subuid range'
  ansible.builtin.lineinfile:
    path: /etc/subuid
    regexp: '^dockremap:'
    line: 'dockremap:1000000:65536'
    create: true
    owner: root
    group: root
    mode: "0644"
    state: present
  notify: restart docker

- name: 'pul_nomad | nomad | docker | add dockremap subgid range'
  ansible.builtin.lineinfile:
    path: /etc/subgid
    regexp: '^dockremap:'
    line: 'dockremap:1000000:65536'
    create: true
    owner: root
    group: root
    mode: "0644"
    state: present
  notify: restart docker

- name: 'pul_nomad | nomad | docker | create docker config directory'
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: 'pul_nomad | nomad | docker | write daemon.json'
  ansible.builtin.copy:
    content: "{{ docker_daemon_config | to_nice_json }}\n"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
    validate: 'dockerd --validate --config-file=%s'
  vars:
    docker_daemon_config:
      userns-remap: dockremap
      log-driver: json-file
      log-opts:
        max-size: 10m
        max-file: "3"
  notify: restart docker

- name: 'pul_nomad | nomad | docker | ensure Docker service is enabled and started'
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: 'pul_nomad | nomad | docker | add pulsys to docker group'
  ansible.builtin.user:
    name: pulsys
    groups: docker
    append: true

# Containers should be able to query nomad if they want and our ACLs allow it.
- name: 'pul_nomad | nomad | docker | allow container access to Nomad API'
  community.general.ufw:
    rule: allow
    direction: in
    interface: docker0
    to_port: '4646'
    proto: tcp
    comment: nomad api for containers
  when: running_on_server
  become: true

- name: 'pul_nomad | nomad | docker | Allow container DNS resolution'
  community.general.ufw:
    rule: allow
    direction: in
    interface: docker0
    to_port: '53'
    proto: "{{ item }}"
    comment: dns for containers
  loop:
    - udp
    - tcp
  when: running_on_server
  become: true

- name: 'pul_nomad | nomad | docker | Allow OTEL'
  community.general.ufw:
    rule: allow
    direction: in
    interface: docker0
    to_port: '{{ item }}'
    proto: "tcp"
    comment: otel for containers
  loop:
    - 4317
    - 4318
  when: running_on_server
  become: true

- name: 'pul_nomad | nomad | docker | Allow containers to talk to Consul'
  community.general.ufw:
    rule: allow
    direction: in
    interface: docker0
    to_port: '8500'
    proto: "{{ item }}"
    comment: dns for containers
  loop:
    - udp
    - tcp
  when: running_on_server
  become: true

- name: 'pul_nomad | nomad | docker | Allow containers to talk to containers'
  community.general.ufw:
    rule: allow
    direction: in
    interface: docker0
    # These are the internal docker IPs.
    from_ip: 172.17.0.0/16
    proto: "tcp"
    comment: Allow containers to talk to other containers by host IP
  when: running_on_server
  become: true

# UFW doesn't apply to docker ports without this block.
# See
# https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-5a-be-careful-when-mapping-container-ports-to-the-host-with-firewalls-like-ufw
# and https://github.com/chaifeng/ufw-docker#solving-ufw-and-docker-issues
- name: 'pul_nomad | nomad | docker | Ensure containers are blocked by UFW'
  ansible.builtin.blockinfile:
    path: /etc/ufw/after.rules
    marker: "# {mark} UFW AND DOCKER"
    insertafter: EOF
    block: |
      *filter
      :ufw-user-forward - [0:0]
      :ufw-docker-logging-deny - [0:0]
      :DOCKER-USER - [0:0]
      -A DOCKER-USER -j ufw-user-forward

      -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
      -A DOCKER-USER -m conntrack --ctstate INVALID -j DROP
      -A DOCKER-USER -i docker0 -o docker0 -j ACCEPT

      # Traffic leaving containers (egress, -i docker0) may go anywhere.
      -A DOCKER-USER -i docker0 -j RETURN

      # Only allow private IP range and load balancers
      -A DOCKER-USER -o docker0 -s 172.20.80.0/22 -j RETURN
      -A DOCKER-USER -o docker0 -s 128.112.203.146/32 -j RETURN
      -A DOCKER-USER -o docker0 -s 128.112.200.245/32 -j RETURN
      -A DOCKER-USER -o docker0 -s 128.112.201.34/32 -j RETURN
      # We have RabbitMQ running on 5672, let it through on the public network
      # web boxes until we move them to private.
      -A DOCKER-USER -o docker0 -p tcp -s 128.112.0.0/16 --dport 5672 -j RETURN
      -A DOCKER-USER -o docker0 -j ufw-docker-logging-deny
      -A DOCKER-USER -o docker0 -j DROP

      -A DOCKER-USER -j RETURN

      -A ufw-docker-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW DOCKER BLOCK] "
      -A ufw-docker-logging-deny -j DROP

      COMMIT
  when: running_on_server
  notify: reload ufw
