---
- name: pul_nomad | nomad | Install Nomad
  ansible.builtin.import_tasks: install.yml

# We configure_server first because it registers and sets all the Consul
# keys/policies, which configure.yml needs.
- name: pul_nomad | nomad | Configure Nomad Server
  ansible.builtin.import_tasks: configure_server.yml

- name: pul_nomad | nomad | Configure Nomad
  ansible.builtin.import_tasks: configure.yml

- name: pul_nomad | nomad | Start Nomad service
  become: true
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: true
  # Make sure it's healthy before we continue, so there's a leader.
  register: nomadServiceDetails
  until: nomadServiceDetails.status.ActiveState == "active"
  retries: 15
  delay: 5

# Set up consul/nomad auth
- name: pul_nomad | nomad | Create consul auth method for Nomad
  community.general.consul_auth_method:
    name: 'nomad-workloads'
    type: 'jwt'
    description: 'JWT auth method for Nomad services and workloads'
    token: '{{ consul_acl_management_token }}'
    config:
      JWKSURL: "{{ nomad_http_address }}/.well-known/jwks.json"
      JWTSupportedAlgs: 
        - "RS256"
      BoundAudiences: 
        - "consul.io"
      ClaimMappings:
        nomad_namespace: "nomad_namespace"
        nomad_job_id: "nomad_job_id"
        nomad_task: "nomad_task"
        nomad_service: "nomad_service"
  run_once: true
- name: pul_nomad | nomad | Bind Nomad auth method for services
  community.general.consul_binding_rule:
    name: 'nomad-workloads'
    token: '{{ consul_acl_management_token }}'
    auth_method: 'nomad-workloads'
    bind_type: service
    bind_name: '${value.nomad_service}'
    selector: '"nomad_service" in value'
  run_once: true
- name: pul_nomad | nomad | Bind Nomad auth method for tasks
  community.general.consul_binding_rule:
    name: 'nomad-tasks-binding'
    token: '{{ consul_acl_management_token }}'
    auth_method: 'nomad-workloads'
    bind_type: 'role'
    bind_name: 'nomad-tasks-${value.nomad_namespace}'
    selector: '"nomad_service" not in value'
  run_once: true
- name: pul_nomad | nomad | Create consul task role that tasks will be associated with
  community.general.consul_role:
    name: 'nomad-tasks-default'
    token: '{{ consul_acl_management_token }}'
    policies:
      - name: "nomad-task-policy"
  run_once: true
# Bootstrap ACL
# We have to do check/register/act here for idempotence because the nomad_token
# module can't assign a known secret ID, and we want to know the management
# token.
- name: 'pul_nomad | nomad | Register existing nomad acl tokens'
  ansible.builtin.shell:
    cmd: "/usr/local/bin/nomad acl token list || true"
  environment:
    NOMAD_TOKEN: '{{ pul_nomad_management_token }}'
  register: nomad_acl_tokens
  run_once: true
  changed_when: false
- name: 'pul_nomad | nomad | Bootstrap nomad'
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad acl bootstrap -
    stdin: '{{ pul_nomad_management_token }}'
  run_once: true
  retries: 15
  delay: 5
  when:
    - "'Bootstrap Token' not in nomad_acl_tokens.stdout "
