---
nomad_volumes:
  - name: 'figgy-rabbitmq-production'
    count: 1
    node_pool: 'production'
    capacity_min: '3G'
    uid: 1000000
    gid: 1000000
nomad_vars:
  figgy-infrastructure-production:
    RABBITMQ_USER: '{{ vault_rabbit_production_user }}'
    RABBITMQ_PASSWORD: '{{ vault_rabbit_production_password }}'
