---
nomad_volumes:
  - name: 'figgy-rabbitmq-staging-cluster'
    count: 3
    node_pool: 'staging'
    capacity_min: '3G'
    uid: 1000000
    gid: 1000000
  - name: 'figgy-redis-staging-cluster'
    count: 3
    node_pool: 'staging'
    capacity_min: '1G'
    uid: 1000999
    gid: 1000999
nomad_vars:
  figgy-infrastructure-staging:
    RABBITMQ_USER: '{{ vault_rabbit_staging_user }}'
    RABBITMQ_PASSWORD: '{{ vault_rabbit_staging_password }}'
    RABBITMQ_ERLANG_COOKIE: '{{ vault_rabbit_staging_erlang_cookie }}'
    REDIS_PASSWORD: '{{ vault_figgy_redis_staging_password }}'
