---
nomad_volumes:
  - name: 'figgy-rabbitmq-staging'
    count: 1
    node_pool: 'staging'
    capacity_min: '3G'
    uid: 1000000
    gid: 1000000
nomad_vars:
  figgy-infrastructure-staging:
    RABBITMQ_USER: '{{ vault_rabbit_staging_user }}'
    RABBITMQ_PASSWORD: '{{ vault_rabbit_staging_password }}'
