---
- name: Converge
  hosts: all
  vars:
    running_on_server: false
    # Won't actually run, but molecule doesn't run without it.
    db_host: 'localhost'
  become: true
  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
  tasks:
    # Change this when copying to another role
    - name: "Include example"
      ansible.builtin.include_role:
        name: nomad_app
