---
# Central switchboard for app configuration. Each app is only included
# when it's present in `nomad_enabled_apps` (a list). This lets us bring
# up new clusters (e.g., sandbox) without running any app tasks until ready.

- name: Pul_nomad | app_config | set default enable list
  ansible.builtin.set_fact:
    nomad_enabled_apps: "{{ nomad_enabled_apps | default([], true) }}"

# This isn't my favorite, but we don't have a way to split these right now and
# not duplicate tasks.
# Maybe application configs should be a different playbook.
# CircleCI deployer
- name: Pul_nomad | app_config | circleci_deployer
  ansible.builtin.import_tasks: "apps/circleci_deployer.yml"
  when: "'circleci_deployer' in nomad_enabled_apps"
  tags: [app_config, circleci_deployer]

# Grist
- name: Pul_nomad | app_config | grist
  ansible.builtin.import_tasks: "apps/grist.yml"
  when:
    - running_on_server
    - "'grist' in nomad_enabled_apps"
  tags: [app_config, grist]

# Imagecat
- name: Pul_nomad | app_config | imagecat
  ansible.builtin.import_tasks: "apps/imagecat_production.yml"
  when: "'imagecat' in nomad_enabled_apps"
  tags: [app_config, imagecat]

- name: Pul_nomad | app_config | imagecat staging
  ansible.builtin.import_tasks: "apps/imagecat_staging.yml"
  when: "'imagecat' in nomad_enabled_apps"
  tags: [app_config, imagecat]

# Signoz
- name: Pul_nomad | app_config | signoz sandbox
  ansible.builtin.import_tasks: "apps/signoz.yml"
  when: "'signoz' in nomad_enabled_apps"
  tags: [app_config, signoz]

# Traefik wall
- name: Pul_nomad | app_config | traefik_wall
  ansible.builtin.import_tasks: "apps/traefik_wall.yml"
  when: "'traefik_wall' in nomad_enabled_apps"
  tags: [app_config, traefik_wall]
