---
# vars file for bind9
bind9_service_name: bind9
bind9_config_dir: /etc/bind
bind9_options_file: /etc/bind/named.conf.options
bind9_defaults_file: /etc/default/named
# Ubuntu < 20.04 read startup options from this path instead.
bind9_legacy_defaults_file: /etc/default/bind9
bind9_systemd_resolv_conf: /run/systemd/resolve/stub-resolv.conf
