---
# defaults file for roles/oawaiver

# Use Ruby 3.2.3 and install from source
install_ruby_from_source: true
ruby_version_override: "ruby-3.2.3"
# postgres test VM settings
postgres_port: 5432
postgres_version: 15
postgres_host: postgres
postgres_admin_user: postgres
vault_postgres_admin_password: postgres
postgres_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
