---
# capistrano based tasks
- name: Ezproxy | Create app directory
  ansible.builtin.file:
    path: "{{ ezproxy_repo_root }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0750"
    recurse: true
  become: true

- name: Ezproxy | Ensure .ssh directory exists.
  ansible.builtin.file:
    path: "/home/{{ deploy_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Ezproxy | Allow ability to restart ezproxy for {{ deploy_user }}
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: /usr/sbin/service ezproxy restart"
    validate: "visudo -cf %s"

- name: Ezproxy | chmod back permissions
  ansible.builtin.file:
    path: "{{ ezproxy_repo_root }}"
    state: directory
    recurse: true
    mode: "0750"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  become: true

- name: Ezproxy | add geoip ppa
  ansible.builtin.apt_repository:
    repo: "ppa:maxmind/ppa"
    state: present

- name: Ezproxy | install geoupdate
  ansible.builtin.apt:
    name: geoipupdate
    state: present

- name: Ezproxy | add geoip configuration file
  ansible.builtin.template:
    src: geoip_conf.j2
    dest: "/etc/GeoIP.conf"
    mode: "0644"
  when:
    - running_on_server

- name: Ezproxy | run a cronjob to update
  ansible.builtin.cron:
    name: "run the update"
    minute: 49
    hour: 8
    job: "/usr/bin/geoipupdate"
  when:
    - running_on_server
