---
passenger_additional_nginx_packages:
  - "libnginx-mod-http-geoip2={{ nginx_version }}"
  - "libnginx-mod-http-image-filter={{ nginx_version }}"
  - "libnginx-mod-http-xslt-filter={{ nginx_version }}"
  - "libnginx-mod-mail={{ nginx_version }}"
  - "libnginx-mod-stream={{ nginx_version }}"
  - "libnginx-mod-stream-geoip2={{ nginx_version }}"
