---
passenger_pin_nginx_version: true

passenger_additional_nginx_package_names:
  - nginx
  - libnginx-mod-http-geoip2
  - libnginx-mod-http-image-filter
  - libnginx-mod-http-xslt-filter
  - libnginx-mod-mail
  - libnginx-mod-stream
  - libnginx-mod-stream-geoip2
