---
# defaults file for roles/mailcatcher

# Make sure install_mailcatcher is set to false on any server where you
# actually want to send email.
install_mailcatcher: true
mailcatcher_manage_user: true
mailcatcher_version: "0.10.0"
mailcatcher_install_location: /usr/local/bin/mailcatcher
mailcatcher_home: /var/lib/mailcatcher
mailcatcher_user: mailcatcher
mailcatcher_group: mailcatcher
mailcatcher_http_listen_address: 0.0.0.0
mailcatcher_http_port: "1080"
mailcatcher_listen_address: 0.0.0.0
mailcatcher_smtp_listen_address: 0.0.0.0
mailcatcher_smtp_port: "1025"
mailcatcher_ubuntu_packages:
  - build-essential
  - libsqlite3-dev
  - pkg-config
  - ruby-dev
  - software-properties-common

