---
- name: Verify
  hosts: instance
  gather_facts: false
  tasks:
  - name: test for deploy user on sudoers
    lineinfile:
      path: "/etc/sudoers"
      line: "{{ item }}"
      state: present
    loop:
      - "deploy ALL=(ALL) NOPASSWD: /usr/sbin/service sidekiq-workers status"
      - "deploy ALL=(ALL) NOPASSWD: /usr/sbin/service sidekiq-workers restart"
      - "deploy ALL=(ALL) NOPASSWD: /usr/sbin/service sidekiq-workers start"
    check_mode: true
    register: present
    failed_when:
      - present is changed

  - name: sidekiq unit sets LimitNOFILE
    ansible.builtin.command: grep -E '^LimitNOFILE=65536$' /etc/systemd/system/sidekiq-workers.service
    changed_when: false
