---
lego_email: "lsupport@princeton.edu"

openresty_altcha_enable: true

lego_certificates:
  - primary: dataspace-dev.princeton.edu
    domains: [dataspace-dev.princeton.edu]
  - primary: oar-dev.princeton.edu
    domains: [oar-dev.princeton.edu]

openresty_vhosts:
  - name: dataspace-dev.princeton.edu
    upstream: { name: dataspace-dev, server: 10.132.0.5:81 }
    ssl_cert: dataspace-dev.princeton.edu.crt
    ssl_key:  dataspace-dev.princeton.edu.key
    access_log: dataspace-dev.access.log
    client_max_body_size: 100M

  - name: oar-dev.princeton.edu
    upstream: { name: oar-dev, server: 10.132.0.4:81 }
    ssl_cert: oar-dev.princeton.edu.crt
    ssl_key:  oar-dev.princeton.edu.key
    access_log: oar-dev.access.log
    client_max_body_size: 100M
    restrict: true
