---
lego_email: "lsupport@princeton.edu"
openresty_altcha_enable: true

lego_certificates:
  - primary: dataspace-staging.princeton.edu
    domains: [dataspace-staging.princeton.edu]
  - primary: oar-staging.princeton.edu
    domains: [oar-staging.princeton.edu]
  - primary: simrisk.pulcloud.io
    domains: [simrisk.pulcloud.io]

openresty_vhosts:
  - name: dataspace-staging.princeton.edu
    upstream: { name: dataspace-staging, server: 10.132.0.5:81 }
    ssl_cert: dataspace-staging.princeton.edu.crt
    ssl_key:  dataspace-staging.princeton.edu.key
    access_log: dataspace-staging.access.log
    client_max_body_size: 100M
    altcha: true
    altcha_bypass_internal: true

  - name: oar-staging.princeton.edu
    upstream: { name: oar-staging, server: 10.132.0.4:81 }
    ssl_cert: oar-staging.princeton.edu.crt
    ssl_key:  oar-staging.princeton.edu.key
    access_log: oar-staging.access.log
    client_max_body_size: 100M
    altcha: true
    restrict: true
    altcha_bypass_internal: true

  - name: simrisk.pulcloud.io
    upstream: { name: simrisk, server: 10.140.0.17:8765 }
    ssl_cert: simrisk.pulcloud.io.crt
    ssl_key:  simrisk.pulcloud.io.key
    client_max_body_size: 100M
