---
nomad_host_volumes:
  - name: loki
    path: '/container_data/loki'
    read_only: false
    owner: '1002056'
    group: '1002056'
  - name: grafana
    path: '/container_data/grafana'
    read_only: false
