#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Princeton University Library
  description: >-
    Prepare a Proxmox VE node for Veeam Backup & Replication using a non-root
    service account.
  license: MIT
  min_ansible_version: "2.14"
  galaxy_tags: []

dependencies: []
