# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Princeton University Library
  description: Deploy Fleet device management onto a microk8s cluster with Helm
  company: Princeton University Library
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - fleet
    - fleetdm
    - kubernetes
    - microk8s
    - helm
    - mdm

dependencies: []
