---
# vars file for roles/lockers_and_study_spaces
passenger_app_root: "/opt/lockers_and_study_spaces/current/public"
nginx_remove_default_vhost: true
rails_app_name: "lockers_and_study_spaces"
rails_app_directory: "lockers_and_study_spaces"
rails_app_symlinks: []
rails_app_dependencies:
  - zlib1g-dev
  - nodejs
