---
nomad_volumes:
  - name: 'redis-production-cluster'
    count: 4
    node_pool: 'production'
    capacity_min: '1G'
    uid: 1000999
    gid: 1000999
nomad_vars:
  redis-production:
    REDIS_PASSWORD: '{{ vault_nomad_redis_production_password }}'
