---
nomad_volumes:
  - name: 'redis-staging-cluster'
    count: 4
    node_pool: 'staging'
    capacity_min: '1G'
    uid: 1000999
    gid: 1000999
nomad_vars:
  redis-staging:
    REDIS_PASSWORD: '{{ vault_nomad_redis_staging_password }}'
