---
# defaults file for roles/pulibrary.docker_ce
docker_compose_version: "1.25.4"

docker_compose_user: "docker"
docker_compose_group: "docker"
docker_compose_dest: "/usr/local/bin"
docker_compose_cmd_name: "docker-compose"

docker_compose_configure_system_path: false
docker_compose_system_path_prepend: false
