#SPDX-License-Identifier: MIT-0
# handlers file for roles/gateway_nat
---
- name: Restart gateway nat service
  ansible.builtin.systemd_service:
    name: "{{ gateway_nat_service_name }}"
    daemon_reload: true
    enabled: true
    state: restarted
  when: gateway_nat_manage_service | bool
