[ansible_tower]
ansible-exec-node1.princeton.edu
ansible-exec-node2.princeton.edu
ansible-tower1.princeton.edu
ansible-tower2.princeton.edu
[tower_26]
# upgrading to 2.6 requires new architecture
tower26controller1.lib.princeton.edu
tower26controller2.lib.princeton.edu
tower26database1.lib.princeton.edu
tower26exec1.lib.princeton.edu
tower26exec2.lib.princeton.edu
tower26gateway1.lib.princeton.edu
