---
- name: Configure the BitCurator sandbox
  hosts: sandbox-bitcur2.princeton.edu
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/bitcurator/sandbox.yml

  roles:
    - role: xrdp
    - role: ssh_ca_trust
