# by default this playbook runs in the staging environment
# to run in qa, pass '-e runtime_env=qa'
# to run in production, pass '-e runtime_env=production'
- name: Run all DACS playbooks
  hosts: dacs:&{{runtime_env|default('staging')}}
  remote_user: pulsys
  become: true
- ansible.builtin.import_playbook: allsearch_api.yml
  tags:
    - rails
- ansible.builtin.import_playbook: approvals.yml
  tags:
    - rails
- ansible.builtin.import_playbook: bibdata.yml
  tags:
    - rails
- ansible.builtin.import_playbook: dss.yml
  tags:
    - rails
- ansible.builtin.import_playbook: lib_jobs.yml
  tags:
    - rails
- ansible.builtin.import_playbook: lockers_and_study_rooms.yml
  tags:
    - rails
- ansible.builtin.import_playbook: orangelight.yml
  tags:
    - rails
- ansible.builtin.import_playbook: repec.yml
  tags:
    - rails
- ansible.builtin.import_playbook: allsearch_frontend.yml
  tags:
    - vue
- ansible.builtin.import_playbook: static_tables.yml
  tags:
    - vue
- ansible.builtin.import_playbook: pas.yml
  tags:
    - php
