---
- name: Configure NAT gateway host
  hosts: ditto.princeton.edu
  remote_user: pulsys
  become: true
  collections:
    - ansible.posix
  roles:
    - role: gateway_nat
      vars:
        gateway_nat_internal_interface: enp2s0
        gateway_nat_external_interface: enp1s0
        gateway_nat_internal_cidr: 172.20.80.0/22
        gateway_nat_external_cidr: 128.112.200.0/21
        gateway_nat_bidirectional_forward: false
