---
# by default this playbook installs the nagios agent (NRPE) on a host we want to monitor
# you must define the machine or group you want to monitor:
# ansible-playbook playbooks/nagios.yml -e host_list=your_group_or_server
# 
# to build or upgrade the nagios server instead,
# pass the server name and set the nagios_target to 'server'
# ansible-playbook playbooks/nagios.yml -e host_list=nagios -e nagios_task=build_server
- name: build the nagios server or the nagios agent (NRPE)
  hosts: "{{ host_list }}"
  vars:
    goal: "{{ nagios_task | default(install_client) }}"
  roles:
    - nagios
