---
- name: Upgrade redis
  hosts: "{{ runtime_env | default('staging') }}"
  remote_user: pulsys
  become: true

  vars_files:
    - ../group_vars/redis/common.yml
    - ../group_vars/redis/{{ runtime_env | default('staging') }}.yml
    - ../group_vars/redis/vault.yml

  tasks:
  - name: Redis | configure redis ppa
    ansible.builtin.deb822_repository:
      name: redislabs-redis
      types: [deb]
      uris: https://ppa.launchpadcontent.net/redislabs/redis/ubuntu
      suites: ["{{ ansible_facts['distribution_release'] }}"]
      components: [main]
      signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60A0586666DE0BA4B481628ACC59E6B43FA6E3CA"
      state: present
      install_python_debian: true

  - name: Update apt repos
    ansible.builtin.apt:
      update_cache: true

  - name: Redis install the upgraded version
    ansible.builtin.apt:
      name: redis-server
      state: present
      only_upgrade: true

  - name: Redis | Upgrade redis packages
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
      force_apt_get: true

