---
- name: Configure k8s NFS
  hosts: k8s_nfs_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/microk8s/{{ runtime_env | default('staging') }}.yml
  roles:
    - role: k8s_nfs

- name: Configure Microk8s Cluster
  hosts: k8s_microk8s_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/microk8s/{{ runtime_env | default('staging') }}.yml
  roles:
    - role: microk8s_cluster

- name: Configure Microk8s Provisioner
  hosts: k8s_microk8s_primary_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/microk8s/{{ runtime_env | default('staging') }}.yml
  roles:
    - role: k8s_nfs_provisioner

- name: Deploy Signoz
  hosts: k8s_microk8s_primary_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/signoz/{{ runtime_env | default('staging') }}.yml
    - ../group_vars/signoz/vault.yml
  roles:
    - role: signoz_k8s

