---
- name: Configure Cert Auth
  hosts: ssh_crt_auth
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/step_ca/main.yml
    - ../group_vars/all/vars.yml
  roles:
    - role: ssh_ca_trust
