---
- name: Configure Step_CA
  hosts: step_ca
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/step_ca/main.yml
    - ../group_vars/step_ca/vault.yml
  roles:
    - role: step_ca
