---
- name: Configure SigNoz synthetic HTTP telemetry
  hosts: synthetic_signoz_{{ runtime_env | default('staging') }}
  remote_user: pulsys
  become: true

  vars_files:
    - ../group_vars/checkmk/{{ runtime_env | default('staging') }}.yml

  roles:
    - role: otel_collector
