# Required: pass a host group '-e host_group=pdc_describe_staging'
- name: upgrade the gcc on the host group to prepare for node 18
  hosts: '{{ host_group }}'
  remote_user: pulsys
  become: true
  vars_files:
    - ../site_vars.yml
  vars:
    gcc_packages:
      - gcc-11
      - g++-11

  tasks:
    - name: Ensure python3-debian is installed for deb822_repository
      ansible.builtin.apt:
        name: python3-debian
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: add the gcc repository
      ansible.builtin.deb822_repository:
        name: ubuntu-toolchain-r-test
        types: [deb]
        uris: https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu
        suites: ["{{ ansible_facts['distribution_release'] }}"]
        components: [main]
        signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC8EC952E2A0E1FBDC5090F6A2C277A0A352154E5"
        state: present
    - name: Update the repository cache and update packages
      ansible.builtin.apt:
        name: "{{ gcc_packages }}"
        state: latest
        update_cache: true

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      community.general.slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}"
        channel: "{{ slack_alerts_channel }}"
      when: not ansible_check_mode
