---
- name: "Install: Install NGINX Otel Module"
  ansible.builtin.apt:
    name: nginx-plus-module-otel
    state: present

- name: "Setup: Load NGINX Otel Module"
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_otel_module.so;
  notify: Reload NGINX
