---

postgres_host: "lib-postgres-prod1.princeton.edu"
postgres_version: 15
postgresql_is_local: false
postgres_admin_user: 'postgres'
postgres_admin_password: '{{ vault_postgres_admin_password }}'

db_host: "{{ postgres_host }}"
db_password: "{{ postgres_admin_password }}"

passenger_server_name: "repec-prod2.princeton.edu"
passenger_app_env: "production"
app_db_host: '{{ db_host }}'
app_db_name: '{{ vault_repec_prod_db_name }}'
app_db_user: '{{ vault_repec_prod_db_user }}'
app_db_password: '{{ vault_repec_prod_db_password }}'
app_secret_key: '{{ vault_repec_prod_secret_key }}'
repec_secret_key_base: '{{ vault_repec_prod_secret_key_base }}'
rails_app_env: "production"
application_db_name: '{{ app_db_name }}'
application_dbuser_name: '{{ app_db_user }}'
application_dbuser_password: '{{ app_db_password }}'
application_dbuser_role_attr_flags: 'CREATEDB'
app_host_name: 'repec-prod.princeton.edu'
application_host_protocol: 'https'

passenger_extra_config: "rewrite ^/econlib/RePEc/pri(.*)$ /$1;"

datadog_api_key: "{{ vault_datadog_key }}"

datadog_config:
  log_enabled: true
  apm_enabled: true
  process_config:
    enabled: true
  apm_config:
    analyzed_spans:
      repec|rack.request: 1
    filter_tags:
      reject: ["http.useragent:nginx/1.23.4 (health check)", "operation:heartbeat", "operation:job_fetch", "operation:scheduled_push", "operation:scheduled_poller_wait"]
datadog_checks:
  tls:
    init_config:
    instances:
      - server: repec.princeton.edu
        port: 443
        tags:
          - 'tls_service:repec'
  repec_datadog_ruby_check:
    init_config:
    logs:
      - type: file
        path: /opt/repec/current/log/production.log
        service: repec
        source: ruby
        sourcecategory: sourcecode
        tags: "repec, environment:production, role:repec"
# beyla
beyla_enabled: true
beyla_service_name: repec
beyla_environment: production
beyla_otlp_endpoint: "http://127.0.0.1:4318"
beyla_otlp_protocol: "http/protobuf"
beyla_bpf_context_propagation: "all"

beyla_open_ports:
  - 80

# signoz
otel_default_resource_attributes:
  host.name: "{{ inventory_hostname }}"
  service.name: repec
  service.version: production
  environment: production

otel_receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  filelog/nginx-access:
    include: ["/var/log/nginx/access.log*"]
    start_at: end
    operators:
      - type: regex_parser
        regex: '^(?P<remote_addr>[^\s]+) \((?P<remote_user>[^)]*)\) - - \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
        parse_from: body
      - type: time_parser
        parse_from: attributes.time_local
        layout_type: strptime
        layout: '%d/%b/%Y:%H:%M:%S %z'
      - type: add
        field: attributes.log_type
        value: "repec_access"
      - type: add
        field: attributes.service_name
        value: repec_access

  filelog/nginx-error:
    include: ["/var/log/nginx/error.log*"]
    start_at: end
    operators:
      - type: add
        field: attributes.log_type
        value: "repec_error"
      - type: add
        field: attributes.service_name
        value: "repec"

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk: {}
      filesystem: {}
      load: {}
      memory: {}
      network: {}

otel_processors:
  batch:
    send_batch_max_size: 1024
    send_batch_size: 512
    timeout: 30s

otel_exporters:
  loadbalancing:
    routing_key: service
    protocol:
      otlp:
        timeout: 10s
        tls:
          insecure: true
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    resolver:
      static:
        hostnames:
          - k8s-prod1.lib.princeton.edu:32317
          - k8s-prod2.lib.princeton.edu:32317
          - k8s-prod3.lib.princeton.edu:32317

  debug:
    verbosity: basic

otel_service_pipelines:
  logs:
    receivers:
      - filelog/nginx-access
      - filelog/nginx-error
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  metrics:
    receivers:
      - hostmetrics
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  traces:
    receivers:
      - otlp
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
