---
# Additional host firewall rules for ZooKeeper servers.
firewall_additional_rules:
  - port: 21047
    protocol: tcp
    source: 10.6.48.214
    comment: Rapid7 Scan Assistant

  # ZooKeeper nodes must accept all traffic from LibNetPvt.
  - rule: allow
    source: 172.20.80.0/22
    comment: PU Subnet - LibNetPvt
