---
# Additional host firewall rules for ZooKeeper servers.
firewall_additional_rules:
  - port: 21047
    protocol: tcp
    source: 10.6.48.214
    comment: Rapid7 Scan Assistant

  - port: 2181
    protocol: tcp
    source: 172.20.80.0/22
    comment: PU Subnet - LibNetPvt

  - port: 2888
    protocol: tcp
    source: 172.20.80.0/22
    comment: PU Subnet - LibNetPvt

  - port: 3888
    protocol: tcp
    source: 172.20.80.0/22
    comment: PU Subnet - LibNetPvt
