---
pulmirror_domain: "pultestmirror.princeton.edu"
pulmirror_domains:
  - "pultestmirror.princeton.edu"

pulmirror_email: "lsupport@princeton.edu"

pulmirror_dns_provider: "dnsimple"
pulmirror_dnsimple_oauth_token: "{{ vault_dnsimple_oauth_token }}"

pulmirror_path: "/usr/local/etc/lego"
pulmirror_nginx_conf: "/usr/local/etc/nginx/conf.d/pultestmirror.princeton.edu.conf"

pulmirror_ssl_certificate: "/usr/local/etc/lego/certificates/pultestmirror.princeton.edu.crt"
pulmirror_ssl_certificate_key: "/usr/local/etc/lego/certificates/pultestmirror.princeton.edu.key"

pulmirror_use_staging: true
