---
- name: reload remote postgres
  ansible.builtin.service:
    name: "{{ postgres_service_name }}"
    state: reloaded
  become: true
  delegate_to: '{{ postgres_host }}'
  # in the old pg_hba tasks file, reloading was delegated like this:
  # delegate_to: "{{ postgres_host | default(inventory_hostname) }}"
  # is this pair of conditions functionally the same?
  when:
    - (postgres_host | default('') | length) > 0
    - not postgresql_is_local

- name: reload local postgres
  ansible.builtin.service:
    name: "{{ postgres_service_name }}"
    state: reloaded
  become: true
  when: postgresql_is_local | bool

- name: save repmgr log
  ansible.builtin.copy:
    content: "{{ repmgr_log }}"
    dest: "{{ repmgr_init_log }}"
    mode: 0644

- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgres_service_name }}"
    state: restarted
  become: true
