---
- name: reload local postgres
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: reloaded
  become: true

- name: save repmgr log
  ansible.builtin.copy:
    content: "{{ repmgr_log }}"
    dest: "{{ repmgr_init_log }}"
    mode: 0644

- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: restarted
  become: true
