---
- name: reload remote postgres
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: reloaded
  become: true
  delegate_to: "{{ postgres_host | default(inventory_hostname, true) }}"
  # in the old pg_hba tasks file, reloading was delegated like this:
  # delegate_to: "{{ postgres_host | default(inventory_hostname) }}"
  # is this pair of conditions functionally the same?
  when:
    - (postgres_host | default('', true) | length) > 0

- name: reload local postgres
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: reloaded
  become: true

- name: save repmgr log
  ansible.builtin.copy:
    content: "{{ repmgr_log }}"
    dest: "{{ repmgr_init_log }}"
    mode: 0644

- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgres_service_name | default(postgresql) }}"
    state: restarted
  become: true
